#!/usr/bin/env python3
"""
Build the TrustBuildGTA site.

  python3 tools/build.py

Every page is generated, homepage included, as one self-contained HTML file
at the repo root (index.html, services.html, basement-renovation.html, ...).

Links between pages are relative (e.g. href="services.html"), so the site
works on any static host, in a subfolder, and when opened straight from disk.
Canonical URLs and the sitemap use the clean form (/services), which Netlify,
Cloudflare Pages and GitHub Pages serve from services.html.

Sources:
  tools/content.py     copy for service and city landing pages
  tools/home_faq.json  the eight general FAQ answers (FAQ page)
  src/partials/*.html  hand-written sections (services grid, gallery, process...)
  src/site.css         styles for every page
  src/site.js          behaviour for every page

The build lints every page (banned words, em/en dashes, meta description
length, one H1, duplicate ids, root-absolute links) and fails if anything is off.
"""
import datetime
import html
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from content import SERVICES, CITIES, CITIES_ORDER, PROCESS  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE = "https://www.trustbuildgta.com"
PHONE = "(647) 513-7955"
TEL = "tel:+16475137955"
CSS = (ROOT / "src" / "site.css").read_text().rstrip()
JS = (ROOT / "src" / "site.js").read_text().rstrip()
HOME_FAQ = json.loads((ROOT / "tools" / "home_faq.json").read_text())

BANNED = ["elevate", "seamless", "transform", "unlock", "dream home", "nestled", "testament",
          "look no further", "one-stop", "tailored", "bespoke", "cutting-edge", "state-of-the-art",
          "world-class", "fast-paced", "pride ourselves", "your vision", "top-notch", "second to none",
          "whether", "journey"]

EXTRA_WORK = "Drywall, trim, painting or addition"

# Section pages that replace the old long homepage. Order = header order.
SECTIONS = [
    ("services", "Services"),
    ("projects", "Projects"),
    ("process", "Process"),
    ("areas", "Areas"),
    ("faq", "FAQ"),
    ("contact", "Contact"),
]


def e(s):
    """Escape text for HTML text and attribute positions."""
    return html.escape(str(s), quote=True)


def link(slug):
    """Relative link to a page. Works on a host, in a subfolder and from disk."""
    return "index.html" if slug in ("", "index") else f"{slug}.html"


def canonical(slug):
    return SITE + "/" if slug in ("", "index") else f"{SITE}/{slug}"


def partial(name):
    return (ROOT / "src" / "partials" / f"{name}.html").read_text().rstrip()


def img_url(pid, w, h=None, q=72):
    url = f"https://images.unsplash.com/photo-{pid}?auto=format&fit=crop&w={w}&q={q}"
    return url + (f"&h={h}" if h else "")


def first_sentence(text):
    return text.split(". ")[0].rstrip(".") + "."


ARROW = ('<svg viewBox="0 0 16 16" aria-hidden="true"><path d="M1 8h13M9 3l5 5-5 5" '
         'fill="none" stroke="currentColor" stroke-width="1.6"/></svg>')

ADDRESS = {
    "@type": "PostalAddress",
    "streetAddress": "8 Matheson Blvd E",
    "addressLocality": "Mississauga",
    "addressRegion": "ON",
    "postalCode": "L4W 2V3",
    "addressCountry": "CA",
}

BUSINESS = {
    "@type": "GeneralContractor",
    "@id": f"{SITE}/#business",
    "name": "TrustBuildGTA",
    "url": SITE,
    "telephone": "+1-647-513-7955",
    "priceRange": "$$",
    "address": ADDRESS,
}


# ======================================================================
# Shared chrome: head, header, footer, script
# ======================================================================

EARLY = """<!-- Flag JS so scroll reveals only hide content when they can also show it -->
  <script>document.documentElement.classList.add('js');</script>"""


def head(title, desc, slug, og_img, schema):
    url = canonical(slug)
    blocks = "\n".join(
        f'  <script type="application/ld+json">\n{json.dumps(s, indent=2, ensure_ascii=False)}\n  </script>'
        for s in schema)
    og = e(img_url(og_img, 1200, 630, 80))
    return f"""<!DOCTYPE html>
<html lang="en-CA">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Generated by tools/build.py. Do not edit this file by hand. -->
  <title>{e(title)}</title>
  <meta name="description" content="{e(desc)}">
  <link rel="canonical" href="{url}">
  <meta name="robots" content="index, follow">
  <meta name="theme-color" content="#14212B">

  <meta property="og:type" content="website">
  <meta property="og:locale" content="en_CA">
  <meta property="og:site_name" content="TrustBuildGTA">
  <meta property="og:title" content="{e(title)}">
  <meta property="og:description" content="{e(desc)}">
  <meta property="og:url" content="{url}">
  <!-- Swap for a 1200x630 photo of a real TrustBuildGTA project -->
  <meta property="og:image" content="{og}">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{e(title)}">
  <meta name="twitter:description" content="{e(desc)}">
  <meta name="twitter:image" content="{og}">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="preconnect" href="https://images.unsplash.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Archivo:wght@700;800&amp;family=Public+Sans:wght@400;500;600&amp;family=Source+Serif+4:ital,wght@1,400;1,500&amp;display=swap">

  {EARLY}

{blocks}

  <style>
{CSS}
  </style>
</head>
"""


def header(current):
    """Skip link and site header. `current` is the page slug."""

    def cur(slug):
        return ' aria-current="page"' if slug == current else ""

    def a(slug, label, load=None, indent=14):
        return (" " * indent + f'<li><a href="{link(slug)}"{cur(slug)}>'
                f'{e(label)}</a></li>')

    svc = "\n".join(a(s["slug"], s["name"]) for s in SERVICES)
    city = "\n".join(a(c["slug"], c["name"]) for c in CITIES)
    msvc = "\n".join(a(s["slug"], s["name"], indent=16) for s in SERVICES)
    mcity = "\n".join(a(c["slug"], c["name"], indent=16) for c in CITIES)
    in_services = current == "services" or current in [s["slug"] for s in SERVICES]
    in_areas = current == "areas" or current in [c["slug"] for c in CITIES]

    def top(slug, label):
        return f'<li><a href="{link(slug)}"{cur(slug)}>{e(label)}</a></li>'

    return f"""<a class="skip" href="#main">Skip to content</a>

  <header class="site-header" id="top">
    <div class="wrap header-bar">
      <a class="logo" href="{link('index')}" aria-label="TrustBuildGTA home">
        <span class="logo__mark" aria-hidden="true"></span>
        <span aria-hidden="true">TrustBuild<span class="logo__gta">GTA</span></span>
      </a>

      <nav class="nav-desktop" aria-label="Main">
        <ul>
          <li class="nav-drop{' is-current' if in_services else ''}" data-dropdown>
            <button class="nav-drop__btn" type="button" aria-expanded="false" aria-controls="dd-services">Services<span class="nav-drop__caret" aria-hidden="true"></span></button>
            <ul class="nav-drop__menu" id="dd-services">
              <li><a href="{link('services')}"{cur('services')}>All services</a></li>
{svc}
            </ul>
          </li>
          {top('projects', 'Projects')}
          {top('process', 'Process')}
          <li class="nav-drop{' is-current' if in_areas else ''}" data-dropdown>
            <button class="nav-drop__btn" type="button" aria-expanded="false" aria-controls="dd-areas">Areas<span class="nav-drop__caret" aria-hidden="true"></span></button>
            <ul class="nav-drop__menu" id="dd-areas">
              <li><a href="{link('areas')}"{cur('areas')}>All service areas</a></li>
{city}
            </ul>
          </li>
          {top('faq', 'FAQ')}
          {top('contact', 'Contact')}
        </ul>
      </nav>

      <div class="header-actions">
        <a class="header-phone" href="{TEL}">
          {PHONE}
          <span>Call any time, 24/7</span>
        </a>
        <a class="btn btn--primary header-cta" href="#quote">Get a Quote</a>
        <button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-menu">
          <span class="sr-only">Menu</span>
          <span class="menu-toggle__bars" aria-hidden="true"><span></span><span></span><span></span></span>
        </button>
      </div>
    </div>

    <!-- Mobile slide-down panel -->
    <div class="mobile-panel" id="mobile-menu">
      <div class="mobile-panel__inner">
        <nav class="wrap" aria-label="Mobile">
          <ul>
            <li>
              <a href="{link('services')}"{cur('services')}>Services</a>
              <ul class="mp-sub">
{msvc}
              </ul>
            </li>
            {top('projects', 'Projects')}
            {top('process', 'Process')}
            <li>
              <a href="{link('areas')}"{cur('areas')}>Areas</a>
              <ul class="mp-sub">
{mcity}
              </ul>
            </li>
            {top('faq', 'FAQ')}
            {top('contact', 'Contact')}
          </ul>
          <div class="mobile-panel__foot">
            <a class="btn btn--primary" href="#quote">Get a Quote</a>
            <a class="btn btn--line" href="{TEL}">Call {PHONE}</a>
            <p class="mobile-panel__hours">Call any time, 24/7</p>
          </div>
        </nav>
      </div>
    </div>
  </header>"""


def footer():
    svc = "\n".join(f'            <li><a href="{link(s["slug"])}">{e(s["name"])}</a></li>' for s in SERVICES)
    cities = "\n".join(f'            <li><a href="{link(c["slug"])}">{e(c["name"])}</a></li>' for c in CITIES)
    company = "\n".join(f'            <li><a href="{link(slug)}">{e(label)}</a></li>'
                        for slug, label in SECTIONS if slug != "services")
    return f"""<!-- Footer. NAP must match the Google Business Profile exactly. -->
  <footer class="site-footer on-dark">
    <div class="wrap">
      <div class="foot-grid">
        <div>
          <a class="logo" href="{link('index')}" aria-label="TrustBuildGTA home">
            <span class="logo__mark" aria-hidden="true"></span>
            <span aria-hidden="true">TrustBuild<span class="logo__gta">GTA</span></span>
          </a>
          <address class="foot-nap">
            <strong>TrustBuildGTA</strong><br>
            8 Matheson Blvd E, Mississauga, ON L4W 2V3<br>
            <a href="{TEL}">{PHONE}</a>
          </address>
          <p class="foot-hours">Open 24 hours, 7 days a week</p>
          <a class="btn btn--primary" href="#quote">Get a Quote</a>
        </div>

        <nav aria-label="Services">
          <p class="foot-h">Services</p>
          <ul>
{svc}
          </ul>
        </nav>

        <nav aria-label="Service areas">
          <p class="foot-h">Areas</p>
          <ul>
{cities}
          </ul>
        </nav>

        <nav aria-label="Company">
          <p class="foot-h">Company</p>
          <ul>
{company}
          </ul>
        </nav>
      </div>

      <div class="foot-base">
        <p>Serving Mississauga, Oakville, Burlington and Hamilton</p>
        <p>&copy; <span id="year">2026</span> TrustBuildGTA</p>
      </div>
    </div>
  </footer>

  <!-- Sticky mobile call/quote bar -->
  <nav class="mbar" aria-label="Quick contact">
    <a href="{TEL}">
      <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.6 10.8a15.1 15.1 0 0 0 6.6 6.6l2.2-2.2a1 1 0 0 1 1-.25 11.4 11.4 0 0 0 3.6.57 1 1 0 0 1 1 1V20a1 1 0 0 1-1 1A17 17 0 0 1 3 4a1 1 0 0 1 1-1h3.5a1 1 0 0 1 1 1c0 1.25.2 2.45.57 3.6a1 1 0 0 1-.25 1z" fill="currentColor"/></svg>
      Call
    </a>
    <a href="#quote">Quote</a>
  </nav>"""


def page_shell(head_html, current, main_html):
    return f"""{head_html}
<body>
  {header(current)}

  <main id="main">
{main_html}
  </main>

  {footer()}

  <script>
{JS}
  </script>
</body>
</html>
"""


# ======================================================================
# Reusable blocks
# ======================================================================

def faq_schema(faq):
    return {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": a}}
            for q, a in faq
        ],
    }


def breadcrumbs_schema(items):
    """items: list of (name, slug)."""
    return {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": n, "item": canonical(slug)}
            for i, (n, slug) in enumerate(items)
        ],
    }


def crumbs_html(items):
    lis = []
    for i, (name, slug) in enumerate(items):
        if i == len(items) - 1:
            lis.append(f'<li aria-current="page">{e(name)}</li>')
        else:
            lis.append(f'<li><a href="{link(slug)}">{e(name)}</a></li>')
    return f'<nav class="crumbs" aria-label="Breadcrumb"><ol>{"".join(lis)}</ol></nav>'


def trust_strip():
    return """    <div class="trust on-dark" role="region" aria-label="Why homeowners trust us">
      <div class="wrap">
        <ul>
          <li>Licensed &amp; insured</li>
          <li>WSIB covered</li>
          <li>Written fixed-price quotes</li>
          <li>Call any time, 24/7</li>
          <li>[X]-year workmanship warranty</li>
        </ul>
      </div>
    </div>"""


def section_head(eyebrow, h2, lede, hid):
    return f"""        <div class="section-head reveal">
          <div>
            <p class="eyebrow">{e(eyebrow)}</p>
            <h2 id="{hid}">{e(h2)}</h2>
          </div>
          <p class="lede">{e(lede)}</p>
        </div>"""


def lead_form(fid, service=None, city=None, wrap_class=""):
    """The one quote form used everywhere. Service pages fix the service, city
    pages fix the city, every other page asks for both."""
    city_opts = "".join(f"<option>{c}</option>" for c in CITIES_ORDER) + "<option>Somewhere nearby</option>"
    proj_opts = "".join(f"<option>{e(s['name'])}</option>" for s in SERVICES)
    proj_opts += f"<option>{EXTRA_WORK}</option><option>Not sure yet</option>"
    tags, fixed, selects = [], [], []

    if service:
        fixed.append(f'<input type="hidden" name="service" value="{e(service)}">')
        tags.append(service)
    else:
        selects.append(f"""<div class="field">
              <label for="{fid}-project">Type of project</label>
              <select id="{fid}-project" name="project" required aria-describedby="{fid}-project-err">
                <option value="">Choose one</option>{proj_opts}
              </select>
              <p class="err" id="{fid}-project-err"></p>
            </div>""")
    if city:
        fixed.append(f'<input type="hidden" name="city" value="{e(city)}">')
        tags.append(city)
    else:
        selects.append(f"""<div class="field">
              <label for="{fid}-city">City</label>
              <select id="{fid}-city" name="city" required aria-describedby="{fid}-city-err">
                <option value="">Choose a city</option>{city_opts}
              </select>
              <p class="err" id="{fid}-city-err"></p>
            </div>""")
    tag_html = "".join(f'<p class="lform__tag">{e(t)}</p> ' for t in tags)
    select_html = (f'<div class="row-2">{"".join(selects)}</div>' if len(selects) == 2 else "".join(selects))

    return f"""<div class="{wrap_class}" id="quote">
          <!-- Posts JSON to FORM_ENDPOINT in the shared script. Name and phone are the only required details. -->
          <form class="qform lform" id="{fid}" data-lead="short" data-done="{fid}-done" novalidate>
            <p class="lform__title">Get a free, fixed-price quote</p>
            <p class="lform__sub">Takes about a minute. A project lead calls you back to book a site visit.</p>
            {"".join(fixed)}
            {tag_html}
            <div class="hp" aria-hidden="true">
              <label for="{fid}-hp">Leave this field empty</label>
              <input type="text" id="{fid}-hp" name="tb_hp_field" tabindex="-1" autocomplete="off">
            </div>
            <div class="field">
              <label for="{fid}-name">Name</label>
              <input id="{fid}-name" name="name" type="text" autocomplete="name" required aria-describedby="{fid}-name-err">
              <p class="err" id="{fid}-name-err"></p>
            </div>
            <div class="row-2">
              <div class="field">
                <label for="{fid}-phone">Phone</label>
                <input id="{fid}-phone" name="phone" type="tel" autocomplete="tel" inputmode="tel" required aria-describedby="{fid}-phone-err">
                <p class="err" id="{fid}-phone-err"></p>
              </div>
              <div class="field">
                <label for="{fid}-email">Email <span class="opt">(optional)</span></label>
                <input id="{fid}-email" name="email" type="email" autocomplete="email" aria-describedby="{fid}-email-err">
                <p class="err" id="{fid}-email-err"></p>
              </div>
            </div>
            {select_html}
            <div class="field">
              <label for="{fid}-message">What are you planning? <span class="opt">(optional)</span></label>
              <textarea id="{fid}-message" name="message" rows="3" placeholder="Rough size, what's there now, when you'd like to start."></textarea>
            </div>
            <button class="btn btn--primary lform__submit" type="submit">Get my free quote</button>
            <div class="qstatus qstatus--error" role="alert" hidden></div>
            <p class="qfine">No obligation. We reply within [X] hours, or call {PHONE} any time. Your details are only used for this quote.</p>
          </form>

          <div class="qform qdone" id="{fid}-done" tabindex="-1" hidden>
            <div class="qdone__mark" aria-hidden="true">
              <svg viewBox="0 0 16 16"><path d="M2 8.5l4 4 8-9" fill="none" stroke="currentColor" stroke-width="2"/></svg>
            </div>
            <p class="lform__title">Got it. Thanks.</p>
            <p>Here's what happens next:</p>
            <ol>
              <li>A project lead calls you, usually within [X] hours.</li>
              <li>We book a site visit at a time that suits you.</li>
              <li>You get a written, fixed-price quote with HST shown.</li>
            </ol>
            <p>In a hurry? Call <a href="{TEL}">{PHONE}</a>. We pick up any time, 24/7.</p>
          </div>
        </div>"""


def contact_section(fid, h2="Get a written quote",
                    lede="Name and phone are all we need. A project lead calls you back to book a site visit. If it's urgent, just call.",
                    bg=""):
    """Form plus contact details. Identical on the homepage, the contact page and every section page."""
    cities = ", ".join(f'<a href="{link(c["slug"])}">{e(c["name"])}</a>' for c in CITIES)
    return f"""    <section class="section {bg}" id="contact" aria-labelledby="contact-title">
      <div class="wrap">
{section_head("Contact", h2, lede, "contact-title")}
        <div class="quote">
          {lead_form(fid, wrap_class="reveal")}

          <aside class="contact-card reveal" aria-label="Contact details">
            <h3>Talk to a person</h3>
            <dl>
              <dt>Phone</dt>
              <dd><a class="big-phone" href="{TEL}">{PHONE}</a></dd>
              <dt>Hours</dt>
              <dd>Call any time, 24/7</dd>
              <dt>Office</dt>
              <dd>
                <address>
                  TrustBuildGTA<br>
                  8 Matheson Blvd E, Mississauga, ON L4W 2V3
                </address>
              </dd>
              <dt>Email</dt>
              <dd><a href="mailto:[EMAIL]">[EMAIL]</a></dd>
              <dt>Serving</dt>
              <dd>{cities}</dd>
            </dl>
            <!-- REAL PHOTO: the project lead or crew on a real job site, landscape, faces optional -->
            <figure class="contact-img ph">
              <img src="{e(img_url('1504307651254-35680f356dfd', 900, 675, 70))}"
                   width="900" height="675" loading="lazy" decoding="async"
                   alt="Crew framing walls on a renovation site">
            </figure>
          </aside>
        </div>
      </div>
    </section>"""


def page_hero(crumbs, eyebrow, h1, lede, extra=""):
    """Compact header for section pages (Services, Projects, Process...)."""
    return f"""    <section class="phero" aria-labelledby="page-title">
      <div class="wrap">
        {crumbs_html(crumbs)}
        <p class="eyebrow">{e(eyebrow)}</p>
        <h1 id="page-title">{e(h1)}</h1>
        <p class="phero__lede">{e(lede)}</p>
        {extra}
      </div>
    </section>"""


def faq_section(faq, h2, prefix, bg=""):
    items = []
    for i, (q, a) in enumerate(faq, 1):
        items.append(f"""          <div class="acc__item">
            <h3><button class="acc__btn" type="button" aria-expanded="false" aria-controls="{prefix}-a{i}" id="{prefix}-q{i}">{e(q)}<span class="acc__icon" aria-hidden="true"></span></button></h3>
            <div class="acc__panel" id="{prefix}-a{i}" role="region" aria-labelledby="{prefix}-q{i}"><div><p>{e(a)}</p></div></div>
          </div>""")
    return f"""    <section class="section {bg}" id="faq" aria-labelledby="faq-title">
      <div class="wrap faq">
        <div class="faq__head reveal">
          <p class="eyebrow">FAQ</p>
          <h2 id="faq-title">{e(h2)}</h2>
          <p class="lede">Don't see yours? Call {PHONE}. Someone picks up any time, 24/7.</p>
        </div>
        <div class="acc reveal">
{chr(10).join(items)}
        </div>
      </div>
    </section>"""


def cta_band(h2, p):
    return f"""    <section class="cta-band on-dark" aria-labelledby="cta-title">
      <div class="wrap cta-band__grid reveal">
        <div>
          <h2 id="cta-title">{e(h2)}</h2>
          <p>{e(p)}</p>
        </div>
        <div class="cta-band__btns">
          <a class="btn btn--primary" href="#quote">Get a Free Quote</a>
          <a class="btn btn--ghost-light" href="{TEL}">Call {PHONE}</a>
        </div>
      </div>
    </section>"""


# ======================================================================
# Homepage (short: teasers that point to the section pages)
# ======================================================================

def home_page():
    schema = [
        dict({"@context": "https://schema.org"}, **BUSINESS, **{
            "image": img_url("1600585154340-be6161a56a0c", 1200, None, 80),
            "openingHoursSpecification": [{
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
                "opens": "00:00", "closes": "23:59"}],
            "areaServed": [{"@type": "City", "name": c} for c in CITIES_ORDER],
            "hasOfferCatalog": {
                "@type": "OfferCatalog",
                "name": "Renovation and general contracting services",
                "itemListElement": [
                    {"@type": "Offer", "itemOffered": {"@type": "Service", "name": s["name"], "url": canonical(s["slug"])}}
                    for s in SERVICES
                ] + [{"@type": "Offer", "itemOffered": {"@type": "Service", "name": "General home contracting: drywall, trim, painting and additions"}}],
            },
        }),
        breadcrumbs_schema([("Home", "index")]),
    ]

    rows = []
    for i, s in enumerate(SERVICES, 1):
        pid, alt, _note = s["hero"]
        rows.append(f"""          <li class="reveal">
            <!-- REAL PHOTO: finished {e(s["name"].lower())} job, crops to 4:3 -->
            <div class="svc-rows__thumb ph"><img src="{e(img_url(pid, 480, 360))}" width="480" height="360" loading="lazy" decoding="async" alt="{e(alt)}"></div>
            <h3>{e(s["name"])}</h3>
            <p>{e(first_sentence(s["sub"]))}</p>
            <a class="arrow-link" href="{link(s["slug"])}">Learn more<span class="sr-only"> about {e(s["name"].lower())}</span> {ARROW}</a>
          </li>""")

    # Recent work mosaic: first photo is the big one
    recent = [
        ("1600210492486-724fe5c67fb0", "Finished basement in Erin Mills with LVP flooring and pot lights", "Erin Mills, Mississauga", "Basement"),
        ("1484154218962-a197022b5858", "White kitchen in Glen Abbey with quartz counters and a tiled backsplash", "Glen Abbey, Oakville", "Kitchen"),
        ("1584622650111-993a426fbf0a", "Ensuite in Millcroft with a floating vanity and porcelain wall tile", "Millcroft, Burlington", "Bathroom"),
        ("1600047509807-ba8f99d2cdde", "Interlock patio and low retaining wall in an Ancaster backyard", "Ancaster, Hamilton", "Outdoor"),
        ("1586023492125-27b2c045efd7", "Wide-plank engineered oak flooring through a Bronte living room", "Bronte, Oakville", "Flooring"),
    ]
    mosaic = []
    for i, (pid, alt, place, kind) in enumerate(recent):
        w, h = (1200, 1200) if i == 0 else (700, 525)
        mosaic.append(f"""          <li class="mosaic__item{' mosaic__item--big' if i == 0 else ''} reveal">
            <!-- REAL PHOTO: {e(kind.lower())} project in {e(place)} -->
            <a href="{link('projects')}" class="ph">
              <img src="{e(img_url(pid, w, h))}" width="{w}" height="{h}" loading="lazy" decoding="async" alt="{e(alt)}">
              <span class="mosaic__cap"><strong>{e(kind)}</strong> {e(place)}</span>
            </a>
          </li>""")

    promises = [
        ("Written fixed-price quotes", "Every line priced and HST shown. Changes come as a written change order, priced first."),
        ("One point of contact", "Your project lead is on site, knows your house and answers their phone."),
        ("Permits handled", "We apply, book inspections and meet the inspector under the Ontario Building Code."),
        ("Site cleaned daily", "Floor protection, dust walls, and a swept site before we leave each day."),
    ]
    promise_html = "".join(f"<li class=\"reveal\"><h3>{e(t)}</h3><p>{e(d)}</p></li>" for t, d in promises)

    main = f"""{partial("home-hero")}

    <section class="section" id="services" aria-labelledby="services-title">
      <div class="wrap">
{section_head("Services", "Basement renovation, kitchens, bathrooms, floors and the concrete patio", "Six kinds of work make up most of our calendar. Each has its own page with what's included, how we build it and what moves the price.", "services-title")}
        <ol class="svc-rows svc-rows--thumbs">
{chr(10).join(rows)}
        </ol>
        <p class="more-link reveal"><a class="btn btn--line" href="{link('services')}">See all services</a></p>
      </div>
    </section>

    <section class="section bg-limestone" id="recent" aria-labelledby="recent-title">
      <div class="wrap">
{section_head("Recent work", "Recent kitchens, bathrooms, basements and backyards", "A few finished jobs from across the four cities. The full gallery, with a before and after, is on the Projects page.", "recent-title")}
        <ul class="mosaic">
{chr(10).join(mosaic)}
        </ul>
        <p class="more-link reveal"><a class="btn btn--line" href="{link('projects')}">See all projects</a></p>
      </div>
    </section>

    <section class="section" id="featured" aria-labelledby="featured-title">
      <div class="wrap teaser">
        <!-- REAL PHOTO: the finished Lorne Park kitchen (same job as the before/after on the Projects page) -->
        <figure class="teaser__img ph reveal">
          <img src="{e(img_url('1556912173-3bb406ef7e77', 1400, 933))}" width="1400" height="933" loading="lazy" decoding="async"
               alt="Finished kitchen in Lorne Park with new cabinets, quartz counters and an island">
        </figure>
        <div class="teaser__body reveal">
          <p class="eyebrow">Featured project</p>
          <h2 id="featured-title">Kitchen renovation in Lorne Park</h2>
          <p>A 1970s side-split, opened up. The wall to the dining room came out, an engineered beam went in, and engineered oak runs through the main floor with no seam at the old doorway. [X weeks] on site.</p>
          <p class="teaser__links">
            <a class="arrow-link" href="{link('projects')}">See the before and after {ARROW}</a>
          </p>
        </div>
      </div>
    </section>

    <section class="section bg-ink on-dark" id="why" aria-labelledby="why-title">
      <div class="wrap">
{section_head("Why TrustBuildGTA", "The contractor you can check up on", "The name is the promise. This is what it means on your job.", "why-title")}
        <ul class="promise-strip">{promise_html}</ul>
        <p class="more-link reveal"><a class="arrow-link" href="{link('process')}">How a job runs, start to finish {ARROW}</a></p>
      </div>
    </section>

{partial("reviews")}

{contact_section("lead-home")}"""

    return page_shell(
        head("General Contractor Mississauga, Oakville, Burlington & Hamilton | TrustBuildGTA",
             "Basement, kitchen and bathroom renovation, flooring and concrete patios in Mississauga, Oakville, Burlington and Hamilton. Written fixed-price quotes.",
             "index", "1600585154340-be6161a56a0c", schema),
        "index", main)


# ======================================================================
# Section pages (one per header item)
# ======================================================================

SECTION_META = {
    "services": dict(
        title="Renovation Services Mississauga, Oakville, Burlington & Hamilton | TrustBuildGTA",
        desc="Basement, kitchen and bathroom renovation, flooring installation, concrete patios and backyard builds across Mississauga, Oakville, Burlington and Hamilton.",
        eyebrow="Services",
        h1="Renovation Services in Mississauga, Oakville, Burlington & Hamilton",
        lede="Pick a service for the full details: what's included, how we build it, what moves the price and what we see most in your city.",
        og="1600566753190-17f0baa2a6c3"),
    "projects": dict(
        title="Renovation Projects Mississauga, Oakville, Burlington & Hamilton | TrustBuildGTA",
        desc="Before and after photos of TrustBuildGTA basements, kitchens, bathrooms, flooring and outdoor work across Mississauga, Oakville, Burlington and Hamilton.",
        eyebrow="Projects",
        h1="Recent Renovation Projects",
        lede="Finished jobs from Port Credit to Ancaster. Drag the before and after, or filter the gallery by the kind of work you're planning.",
        og="1556912173-3bb406ef7e77"),
    "process": dict(
        title="How We Work: Renovation Process and Guarantees | TrustBuildGTA",
        desc="How a TrustBuildGTA renovation runs: site visit, written fixed-price quote, one project lead, permits and inspections, daily clean-up and a written warranty.",
        eyebrow="Process",
        h1="How a Renovation Runs With Us",
        lede="Four stages, one project lead, and a price that doesn't move unless you sign a change order. Here's what happens and what you get at each step.",
        og="1504307651254-35680f356dfd"),
    "areas": dict(
        title="Service Areas: Mississauga, Oakville, Burlington & Hamilton | TrustBuildGTA",
        desc="TrustBuildGTA is a general contractor serving Mississauga, Oakville, Burlington and Hamilton. See the neighbourhoods we work in and the projects we see most.",
        eyebrow="Service areas",
        h1="General Contractor for Mississauga, Oakville, Burlington & Hamilton",
        lede="From our office near Hurontario and the 401 to the Hamilton Mountain is about an hour on a good day. We don't go further than that, so your project lead can be on site every working day.",
        og="1600047509807-ba8f99d2cdde"),
    "faq": dict(
        title="Renovation FAQ: Costs, Permits, Timelines & Warranty | TrustBuildGTA",
        desc="Answers on renovation costs in Ontario, building permits, kitchen timelines, LVP vs hardwood, concrete vs interlock, design, payment schedules and warranty.",
        eyebrow="FAQ",
        h1="Renovation Questions, Answered",
        lede="The questions we hear every week about cost, permits, timelines and materials. Specific answers, with placeholders where a real number depends on your house.",
        og="1600607687939-ce8a6c25118c"),
    "contact": dict(
        title="Contact TrustBuildGTA | General Contractor in Mississauga, Call 24/7",
        desc="Get a free written quote from TrustBuildGTA. Call (647) 513-7955 any time, 24/7, or send the form. Office at 8 Matheson Blvd E, Mississauga, ON L4W 2V3.",
        eyebrow="Contact",
        h1="Contact TrustBuildGTA",
        lede="Send the form or call. Either way you talk to a project lead, not a call centre, and the next step is a site visit.",
        og="1504307651254-35680f356dfd"),
}


def section_page(slug):
    m = SECTION_META[slug]
    label = dict(SECTIONS)[slug]
    crumbs = [("Home", "index"), (label, slug)]
    schema = [
        {
            "@context": "https://schema.org",
            "@type": "WebPage",
            "name": m["h1"],
            "url": canonical(slug),
            "description": m["desc"],
            "about": {"@id": f"{SITE}/#business"},
        },
        breadcrumbs_schema(crumbs),
    ]
    hero_extra = ""
    if slug == "contact":
        hero_extra = f'<p class="phero__call"><a class="btn btn--primary" href="{TEL}">Call {PHONE}</a> <span>Call any time, 24/7</span></p>'
    hero = page_hero(crumbs, m["eyebrow"], m["h1"], m["lede"], hero_extra)
    fid = f"lead-{slug}"

    if slug == "services":
        body = partial("services-grid") + "\n\n" + contact_section(fid, bg="bg-limestone")
    elif slug == "projects":
        body = partial("featured") + "\n\n" + partial("gallery") + "\n\n" + contact_section(fid, bg="bg-limestone")
    elif slug == "process":
        body = partial("process") + "\n\n" + partial("why") + "\n\n" + contact_section(fid, bg="bg-limestone")
    elif slug == "areas":
        body = partial("areas") + "\n\n" + contact_section(fid, bg="bg-limestone")
    elif slug == "faq":
        schema.append(faq_schema(HOME_FAQ))
        body = faq_section(HOME_FAQ, "Questions we answer every week", "faq") + "\n\n" + contact_section(fid, bg="bg-limestone")
    else:  # contact
        body = contact_section(fid, h2="Send us the details",
                               lede="Name and phone are all we need to start. We reply to set up a site visit, usually the same day.")

    return page_shell(head(m["title"], m["desc"], slug, m["og"], schema), slug, hero + "\n\n" + body)


# ======================================================================
# Service and city landing pages
# ======================================================================

def landing_hero(page, fid, crumbs, eyebrow, service=None, city=None):
    pid, alt, note = page["hero"]
    hero_img = (f'<!-- REAL PHOTO: {e(note)} -->\n'
                f'      <img class="{{cls}}" src="{e(img_url(pid, 2000, 1200, 75))}"\n'
                f'           srcset="{e(img_url(pid, 900, 600, 70))} 900w, {e(img_url(pid, 1400, 840, 72))} 1400w, {e(img_url(pid, 2000, 1200, 75))} 2000w"\n'
                f'           sizes="100vw" width="2000" height="1200" alt="{e(alt)}" fetchpriority="high" decoding="async">')
    ticks = "".join(f"<li>{e(t)}</li>" for t in page["ticks"])
    copy = f"""<div class="lhero__copy">
          {crumbs_html(crumbs)}
          <p class="eyebrow">{e(eyebrow)}</p>
          <h1 id="page-title">{e(page["h1"])}</h1>
          <p class="lhero__sub">{e(page["sub"])}</p>
          <ul class="ticks">{ticks}</ul>
          <p class="lhero__call">Rather talk it through? Call <a href="{TEL}">{PHONE}</a>. Any time, 24/7.</p>
        </div>"""
    form = lead_form(fid, service=service, city=city, wrap_class="lhero__form")
    if page["variant"] == "photo":
        return f"""    <section class="lhero lhero--photo" aria-labelledby="page-title">
      {hero_img.replace("{cls}", "lhero__img")}
      <div class="wrap lhero__grid">
        {copy}
        {form}
      </div>
    </section>
{trust_strip()}"""
    return f"""    <section class="lhero lhero--split" aria-labelledby="page-title">
      <div class="wrap lhero__grid">
        {copy}
        {form}
      </div>
    </section>
    <div class="lband-wrap">
      <div class="wrap">
        <figure class="lband ph">
          {hero_img.replace("{cls}", "lband__img")}
        </figure>
      </div>
    </div>
{trust_strip()}"""


def service_page(s):
    slug = s["slug"]
    crumbs = [("Home", "index"), ("Services", "services"), (s["name"], slug)]
    schema = [
        {
            "@context": "https://schema.org",
            "@type": "Service",
            "name": s["name"],
            "serviceType": s["name"],
            "description": s["desc"],
            "url": canonical(slug),
            "provider": BUSINESS,
            "areaServed": [{"@type": "City", "name": c} for c in CITIES_ORDER],
        },
        breadcrumbs_schema(crumbs),
        faq_schema(s["faq"]),
    ]
    fid = "lead-" + slug

    scope = "\n".join(
        f"""          <li class="scope__group">
            <h3>{e(t)}</h3>
            <ul class="inc">{"".join(f"<li>{e(i)}</li>" for i in items)}</ul>
          </li>""" for t, items in s["scope"])

    pair = []
    for pid, alt, cap, note in s["pair"]:
        pair.append(f"""          <figure class="reveal">
            <!-- REAL PHOTO: {e(note)} -->
            <div class="pair__img ph"><img src="{e(img_url(pid, 1100))}" width="1100" height="733" loading="lazy" decoding="async" alt="{e(alt)}"></div>
            <figcaption>{e(cap)}</figcaption>
          </figure>""")

    method = "\n".join(
        f'          <li class="reveal"><h3>{e(t)}</h3><p>{e(d)}</p></li>' for t, d in s["method"])

    compare_html = ""
    if s.get("compare"):
        c = s["compare"]
        thead = "".join(f'<th scope="col">{e(x)}</th>' for x in c["cols"])
        rows = "".join(
            f'<tr><th scope="row">{e(r)}</th>{"".join(f"<td>{e(v)}</td>" for v in vals)}</tr>'
            for r, vals in c["rows"])
        compare_html = f"""
    <section class="section" id="compare" aria-labelledby="compare-title">
      <div class="wrap">
{section_head("Compare", "Hardwood, engineered, LVP or tile: which floor goes where", "The short version of what we explain at every site visit. Scroll sideways on a phone.", "compare-title")}
        <div class="table-scroll reveal" role="region" aria-label="Flooring comparison table" tabindex="0">
          <table class="compare compare--wide">
            <caption class="sr-only">Comparison of flooring types</caption>
            <thead><tr><th scope="col"><span class="sr-only">Property</span></th>{thead}</tr></thead>
            <tbody>{rows}</tbody>
          </table>
        </div>
      </div>
    </section>"""

    drivers = "".join(f"<li><strong>{e(t)}</strong><span>{e(d)}</span></li>" for t, d in s["drivers"])

    local = []
    for city in CITIES_ORDER:
        local.append(f"""          <article class="area reveal">
            <div class="area__top"><h3>{city}</h3></div>
            <p>{e(s["local"][city])}</p>
            <a class="arrow-link" href="{link(city.lower())}">General contractor in {city}
              {ARROW}</a>
          </article>""")

    related = "\n".join(
        f'          <li><a href="{link(o["slug"])}">{e(o["name"])}{ARROW}</a></li>'
        for o in SERVICES if o["slug"] != slug)

    main = f"""{landing_hero(s, fid, crumbs, "Service", service=s["name"])}

    <section class="section" id="scope" aria-labelledby="scope-title">
      <div class="wrap">
        <div class="split-head reveal">
          <div>
            <p class="eyebrow">What's included</p>
            <h2 id="scope-title">{e(s["intro_h2"])}</h2>
          </div>
          <div class="split-head__body">
            {"".join(f"<p>{e(p)}</p>" for p in s["intro"])}
          </div>
        </div>
        <ul class="scope">
{scope}
        </ul>
        <div class="pair">
{chr(10).join(pair)}
        </div>
      </div>
    </section>
{compare_html}
    <section class="section bg-limestone" id="method" aria-labelledby="method-title">
      <div class="wrap">
{section_head("How we build it", s["method_h2"], s["method_lede"], "method-title")}
        <ol class="method">
{method}
        </ol>
      </div>
    </section>

    <section class="section" id="cost" aria-labelledby="cost-title">
      <div class="wrap price">
        <div class="reveal">
          <p class="eyebrow">Cost</p>
          <h2 id="cost-title">{e(s["price_h2"])}</h2>
          <p class="lede">{e(s["price_intro"])}</p>
          <p class="price__note">Every quote is a fixed price for your house, with HST shown as its own line.</p>
          <p><a class="btn btn--primary" href="#quote">Get your fixed price</a></p>
        </div>
        <div class="reveal">
          <ul class="drivers">{drivers}</ul>
        </div>
      </div>
    </section>

    <section class="section bg-limestone" id="areas" aria-labelledby="areas-title">
      <div class="wrap">
{section_head("Where we work", s["name"] + " in Mississauga, Oakville, Burlington and Hamilton", "The same crew and the same fixed-price quote in all four cities. Here's what we see most in each.", "areas-title")}
        <div class="areas">
{chr(10).join(local)}
        </div>
      </div>
    </section>

{faq_section(s["faq"], s["name"] + " questions", "faq")}

{cta_band(s["cta_h2"], s["cta_p"])}

    <section class="section" id="related" aria-labelledby="related-title">
      <div class="wrap">
{section_head("More services", "Other work we do", "Most jobs turn into two. We quote each one on its own line.", "related-title")}
        <ul class="related reveal">
{related}
        </ul>
      </div>
    </section>"""

    return page_shell(head(s["title"], s["desc"], slug, s["hero"][0], schema), slug, main)


def city_page(c):
    slug = c["slug"]
    crumbs = [("Home", "index"), ("Areas", "areas"), (c["name"], slug)]
    schema = [
        {
            "@context": "https://schema.org",
            "@type": "Service",
            "name": f"General contracting in {c['name']}",
            "serviceType": "General contractor",
            "description": c["desc"],
            "url": canonical(slug),
            "provider": BUSINESS,
            "areaServed": {"@type": "City", "name": c["name"]},
        },
        breadcrumbs_schema(crumbs),
        faq_schema(c["faq"]),
    ]
    fid = "lead-" + slug

    hoods = "".join(f"<li><h3>{e(n)}</h3><p>{e(t)}</p></li>" for n, t in c["hoods"])

    rows = []
    for i, s in enumerate(SERVICES, 1):
        rows.append(f"""          <li class="reveal">
            <span class="svc-rows__n">{i:02d}</span>
            <h3>{e(s["name"])}</h3>
            <p>{e(s["local"][c["name"]])}</p>
            <a class="arrow-link" href="{link(s["slug"])}">Learn more<span class="sr-only"> about {e(s["name"].lower())}</span> {ARROW}</a>
          </li>""")

    steps = []
    for i, (t, d, get) in enumerate(PROCESS, 1):
        steps.append(f"""          <li class="step reveal">
            <span class="step__n" aria-hidden="true">{i:02d}</span>
            <h3>{e(t)}</h3>
            <p>{e(d)}</p>
            <p class="step__get"><strong>You get:</strong> {e(get)}</p>
          </li>""")

    others = "\n".join(
        f'          <li><a href="{link(o["slug"])}">General contractor in {e(o["name"])}{ARROW}</a></li>'
        for o in CITIES if o["slug"] != slug)

    main = f"""{landing_hero(c, fid, crumbs, "Service area", city=c["name"])}

    <section class="section" id="about" aria-labelledby="about-title">
      <div class="wrap">
        <div class="split-head reveal">
          <div>
            <p class="eyebrow">{e(c["name"])}</p>
            <h2 id="about-title">{e(c["intro_h2"])}</h2>
          </div>
          <div class="split-head__body">
            {"".join(f"<p>{e(p)}</p>" for p in c["intro"])}
          </div>
        </div>
        <ul class="hoods reveal">{hoods}</ul>
      </div>
    </section>

    <section class="section bg-limestone" id="services" aria-labelledby="services-title">
      <div class="wrap">
{section_head("Services", "Renovation services in " + c["name"], "Six kinds of work make up most of our calendar here. Each has its own page with the details.", "services-title")}
        <ol class="svc-rows">
{chr(10).join(rows)}
        </ol>
      </div>
    </section>

    <section class="section bg-ink on-dark" id="process" aria-labelledby="process-title">
      <div class="wrap">
{section_head("Process", "How a job runs in " + c["name"], "Four stages. You always know which one you're in and who to call about it.", "process-title")}
        <ol class="steps">
{chr(10).join(steps)}
        </ol>
      </div>
    </section>

{faq_section(c["faq"], "Questions from " + c["name"] + " homeowners", "faq")}

{cta_band("Book a site visit in " + c["name"], "One visit, then a written fixed price with HST shown. Call any time, 24/7.")}

    <section class="section" id="related" aria-labelledby="related-title">
      <div class="wrap">
{section_head("Other areas", "We also work in", "Same crew, same fixed-price quotes.", "related-title")}
        <ul class="related reveal">
{others}
        </ul>
      </div>
    </section>"""

    return page_shell(head(c["title"], c["desc"], slug, c["hero"][0], schema), slug, main)


# ======================================================================
# Lint, sitemap, main
# ======================================================================

def lint(name, text, all_pages):
    problems = []
    visible = re.sub(r"<style.*?</style>|<script(?! type=\"application/ld\+json\").*?</script>", "", text, flags=re.S)
    low = visible.lower()
    for w in BANNED:
        if w in low:
            problems.append(f"banned word '{w}'")
    for ch, label in (("—", "em dash"), ("–", "en dash")):
        if ch in text:
            problems.append(label)
    h1 = len(re.findall(r"<h1[\s>]", text))
    if h1 != 1:
        problems.append(f"{h1} H1 elements")
    m = re.search(r'<meta name="description" content="([^"]*)"', text)
    n = len(html.unescape(m.group(1))) if m else 0
    if not 150 <= n <= 160:
        problems.append(f"meta description is {n} characters (want 150 to 160)")
    ids = re.findall(r'\sid="([^"]+)"', text)
    dup = sorted({i for i in ids if ids.count(i) > 1})
    if dup:
        problems.append(f"duplicate ids {dup}")
    # Internal links must be relative .html links to pages that exist, or in-page anchors
    for href in re.findall(r'href="([^"]+)"', visible):
        if href.startswith(("http", "tel:", "mailto:", "#", "[")):
            continue
        target = href.split("#")[0]
        if target not in all_pages:
            problems.append(f"broken or non-relative link {href!r}")
    for anchor in set(re.findall(r'href="#([^"]+)"', visible)):
        if anchor not in ids:
            problems.append(f"in-page link to missing #{anchor}")
    for p in problems:
        print(f"  LINT {name}: {p}")
    return not problems


def main():
    pages = {"index": home_page()}
    for slug, _ in SECTIONS:
        pages[slug] = section_page(slug)
    for s in SERVICES:
        pages[s["slug"]] = service_page(s)
    for c in CITIES:
        pages[c["slug"]] = city_page(c)

    names = {f"{slug}.html" for slug in pages}
    ok = True
    for slug, text in pages.items():
        (ROOT / f"{slug}.html").write_text(text)
        ok &= lint(slug, text, names)
        print(f"wrote {slug}.html ({len(text) // 1024} KB)")

    today = datetime.date.today().isoformat()
    urls = [canonical(slug) for slug in pages]
    (ROOT / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "".join(f"  <url><loc>{u}</loc><lastmod>{today}</lastmod></url>\n" for u in urls)
        + "</urlset>\n")
    (ROOT / "robots.txt").write_text(f"User-agent: *\nAllow: /\n\nSitemap: {SITE}/sitemap.xml\n")
    print("wrote sitemap.xml and robots.txt")
    if not ok:
        sys.exit(1)


if __name__ == "__main__":
    main()
