#!/usr/bin/env python3
"""
Build the TrustBuildGTA site.

  python3 tools/build.py

What it does:
  1. Writes one self-contained page per service and per city
     (e.g. basement-renovation.html, oakville.html). Netlify, Cloudflare Pages
     and GitHub Pages serve these at /basement-renovation with no redirect,
     which matches the canonical URLs. On Vercel, set "cleanUrls": true.
  2. Refreshes the shared regions of index.html (CSS, header, footer, loader,
     shared script) between the @build markers. Everything else in index.html
     is hand-edited and left alone.
  3. Writes sitemap.xml and robots.txt.
  4. Lints every page: banned words, em/en dashes, meta description length,
     exactly one H1.

Edit copy in tools/content.py, shared styles in src/site.css and shared
behaviour in src/site.js. Never edit the generated pages directly.
"""
import datetime
import html
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from content import SERVICES, CITIES, CITIES_ORDER, PROCESS  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE = "https://www.trustbuildgta.com"
PHONE = "(647) 513-7955"
TEL = "tel:+16475137955"
CSS = (ROOT / "src" / "site.css").read_text().rstrip()
JS = (ROOT / "src" / "site.js").read_text().rstrip()

BANNED = ["elevate", "seamless", "transform", "unlock", "dream home", "nestled", "testament",
          "look no further", "one-stop", "tailored", "bespoke", "cutting-edge", "state-of-the-art",
          "world-class", "fast-paced", "pride ourselves", "your vision", "top-notch", "second to none",
          "whether", "journey"]

EXTRA_WORK = "Drywall, trim, painting or addition"


def e(s):
    """Escape text for HTML text and attribute positions."""
    return html.escape(str(s), quote=True)


def img_url(pid, w, h=None, q=72):
    url = f"https://images.unsplash.com/photo-{pid}?auto=format&fit=crop&w={w}&q={q}"
    return url + (f"&h={h}" if h else "")


ARROW = ('<svg viewBox="0 0 16 16" aria-hidden="true"><path d="M1 8h13M9 3l5 5-5 5" '
         'fill="none" stroke="currentColor" stroke-width="1.6"/></svg>')

BUSINESS = {
    "@type": "GeneralContractor",
    "@id": f"{SITE}/#business",
    "name": "TrustBuildGTA",
    "url": SITE,
    "telephone": "+1-647-513-7955",
    "priceRange": "$$",
    "address": {
        "@type": "PostalAddress",
        "streetAddress": "8 Matheson Blvd E",
        "addressLocality": "Mississauga",
        "addressRegion": "ON",
        "postalCode": "L4W 2V3",
        "addressCountry": "CA",
    },
}


# ======================================================================
# Shared regions
# ======================================================================

EARLY = """<!-- @build:early -->
  <!-- Flag JS, and keep the loader up if we arrived from a header link -->
  <script>(function(d){d.classList.add('js');try{var l=sessionStorage.getItem('tb-nav');if(l){sessionStorage.removeItem('tb-nav');d.classList.add('tb-arriving');d.setAttribute('data-nav-label',l);}}catch(e){}})(document.documentElement);</script>
  <!-- @end:early -->"""


def css_region():
    return f"/* @build:css (generated from src/site.css) */\n{CSS}\n    /* @end:css */"


def header(current="", home=False):
    """Loader overlay, skip link and site header. `current` is the page path."""
    p = "" if home else "/"
    logo_href = "#top" if home else "/"
    contact = "#contact" if home else "#quote"

    def cur(path):
        return ' aria-current="page"' if path == current else ""

    svc_links = "\n".join(
        f'              <li><a href="/{s["slug"]}" data-load="{e(s["name"])}"{cur("/" + s["slug"])}>{e(s["name"])}</a></li>'
        for s in SERVICES)
    city_links = "\n".join(
        f'              <li><a href="/{c["slug"]}" data-load="{e(c["name"])}"{cur("/" + c["slug"])}>{e(c["name"])}</a></li>'
        for c in CITIES)
    mp_svc = "\n".join(
        f'                <li><a href="/{s["slug"]}" data-load="{e(s["name"])}"{cur("/" + s["slug"])}>{e(s["name"])}</a></li>'
        for s in SERVICES)
    mp_city = "\n".join(
        f'                <li><a href="/{c["slug"]}" data-load="{e(c["name"])}"{cur("/" + c["slug"])}>{e(c["name"])}</a></li>'
        for c in CITIES)

    return f"""<!-- @build:header (generated by tools/build.py) -->
  <!-- Page loader: only shown for header navigation -->
  <div class="loader" id="loader" aria-hidden="true">
    <span class="loader__bar"></span>
    <div class="loader__inner">
      <div class="loader__courses"><span></span><span></span><span></span></div>
      <p class="loader__label">Loading</p>
      <p class="loader__brand">TrustBuildGTA</p>
    </div>
  </div>

  <a class="skip" href="#main">Skip to content</a>

  <header class="site-header" id="top">
    <div class="wrap header-bar">
      <a class="logo" href="{logo_href}" data-load="Home" aria-label="TrustBuildGTA home">
        <span class="logo__mark" aria-hidden="true"></span>
        <span aria-hidden="true">TrustBuild<span class="logo__gta">GTA</span></span>
      </a>

      <nav class="nav-desktop" aria-label="Main">
        <ul>
          <li class="nav-drop" data-dropdown>
            <button class="nav-drop__btn" type="button" aria-expanded="false" aria-controls="dd-services">Services<span class="nav-drop__caret" aria-hidden="true"></span></button>
            <ul class="nav-drop__menu" id="dd-services">
              <li><a href="{p}#services" data-load="Services">All services</a></li>
{svc_links}
            </ul>
          </li>
          <li><a href="{p}#projects" data-load="Projects">Projects</a></li>
          <li><a href="{p}#process" data-load="Process">Process</a></li>
          <li class="nav-drop" data-dropdown>
            <button class="nav-drop__btn" type="button" aria-expanded="false" aria-controls="dd-areas">Areas<span class="nav-drop__caret" aria-hidden="true"></span></button>
            <ul class="nav-drop__menu" id="dd-areas">
              <li><a href="{p}#areas" data-load="Service areas">All service areas</a></li>
{city_links}
            </ul>
          </li>
          <li><a href="{p}#faq" data-load="FAQ">FAQ</a></li>
          <li><a href="{contact}" data-load="Contact">Contact</a></li>
        </ul>
      </nav>

      <div class="header-actions">
        <a class="header-phone" href="{TEL}">
          {PHONE}
          <span>Call any time, 24/7</span>
        </a>
        <a class="btn btn--clay header-cta" href="#quote">Get a Quote</a>
        <button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-menu">
          <span class="sr-only">Menu</span>
          <span class="menu-toggle__bars" aria-hidden="true"><span></span><span></span><span></span></span>
        </button>
      </div>
    </div>

    <!-- Mobile slide-down panel -->
    <div class="mobile-panel" id="mobile-menu">
      <div class="mobile-panel__inner">
        <nav class="wrap" aria-label="Mobile">
          <ul>
            <li>
              <a href="{p}#services" data-load="Services">Services</a>
              <ul class="mp-sub">
{mp_svc}
              </ul>
            </li>
            <li><a href="{p}#projects" data-load="Projects">Projects</a></li>
            <li><a href="{p}#process" data-load="Process">Process</a></li>
            <li>
              <a href="{p}#areas" data-load="Service areas">Areas</a>
              <ul class="mp-sub">
{mp_city}
              </ul>
            </li>
            <li><a href="{p}#faq" data-load="FAQ">FAQ</a></li>
            <li><a href="{contact}" data-load="Contact">Contact</a></li>
          </ul>
          <div class="mobile-panel__foot">
            <a class="btn btn--clay" href="#quote">Get a Quote</a>
            <a class="btn btn--line" href="{TEL}">Call {PHONE}</a>
            <p class="mobile-panel__hours">Call any time, 24/7</p>
          </div>
        </nav>
      </div>
    </div>
  </header>
  <!-- @end:header -->"""


def footer(home=False):
    logo_href = "#top" if home else "/"
    quote = "#quote"
    svc = "\n".join(f'            <li><a href="/{s["slug"]}">{e(s["name"])}</a></li>' for s in SERVICES)
    cities = "\n".join(f'            <li><a href="/{c["slug"]}">{e(c["name"])}</a></li>' for c in CITIES)
    return f"""<!-- @build:footer (generated by tools/build.py). NAP must match the Google Business Profile exactly. -->
  <footer class="site-footer on-dark">
    <div class="wrap">
      <div class="foot-grid">
        <div>
          <a class="logo" href="{logo_href}" aria-label="TrustBuildGTA home">
            <span class="logo__mark" aria-hidden="true"></span>
            <span aria-hidden="true">TrustBuild<span class="logo__gta">GTA</span></span>
          </a>
          <address class="foot-nap">
            <strong>TrustBuildGTA</strong><br>
            8 Matheson Blvd E, Mississauga, ON L4W 2V3<br>
            <a href="{TEL}">{PHONE}</a>
          </address>
          <p class="foot-hours">Open 24 hours, 7 days a week</p>
        </div>

        <nav aria-label="Services">
          <p class="foot-h">Services</p>
          <ul>
{svc}
          </ul>
        </nav>

        <nav aria-label="Service areas">
          <p class="foot-h">Areas</p>
          <ul>
{cities}
          </ul>
        </nav>

        <div>
          <p class="foot-h">Start a project</p>
          <p class="foot-hours">A written, fixed-price quote after one site visit.</p>
          <a class="btn btn--clay" href="{quote}">Get a Quote</a>
        </div>
      </div>

      <div class="foot-base">
        <p>Serving Mississauga, Oakville, Burlington and Hamilton</p>
        <p>&copy; <span id="year">2026</span> TrustBuildGTA</p>
      </div>
    </div>
  </footer>

  <!-- Sticky mobile call/quote bar -->
  <nav class="mbar" aria-label="Quick contact">
    <a href="{TEL}">
      <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.6 10.8a15.1 15.1 0 0 0 6.6 6.6l2.2-2.2a1 1 0 0 1 1-.25 11.4 11.4 0 0 0 3.6.57 1 1 0 0 1 1 1V20a1 1 0 0 1-1 1A17 17 0 0 1 3 4a1 1 0 0 1 1-1h3.5a1 1 0 0 1 1 1c0 1.25.2 2.45.57 3.6a1 1 0 0 1-.25 1z" fill="currentColor"/></svg>
      Call
    </a>
    <a href="{quote}">Quote</a>
  </nav>
  <!-- @end:footer -->"""


def js_region():
    return f"""<!-- @build:js (generated from src/site.js) -->
  <script>
{JS}
  </script>
  <!-- @end:js -->"""


# ======================================================================
# Page parts
# ======================================================================

def head(title, desc, path, og_img, schema):
    url = SITE + path
    blocks = "\n".join(
        f'  <script type="application/ld+json">\n{json.dumps(s, indent=2, ensure_ascii=False)}\n  </script>'
        for s in schema)
    og = e(img_url(og_img, 1200, 630, 80))
    return f"""<!DOCTYPE html>
<html lang="en-CA">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Generated by tools/build.py from tools/content.py. Do not edit this file by hand. -->
  <title>{e(title)}</title>
  <meta name="description" content="{e(desc)}">
  <link rel="canonical" href="{url}">
  <meta name="robots" content="index, follow">
  <meta name="theme-color" content="#1C1F1D">

  <meta property="og:type" content="website">
  <meta property="og:locale" content="en_CA">
  <meta property="og:site_name" content="TrustBuildGTA">
  <meta property="og:title" content="{e(title)}">
  <meta property="og:description" content="{e(desc)}">
  <meta property="og:url" content="{url}">
  <!-- Swap for a 1200x630 photo of a real TrustBuildGTA project -->
  <meta property="og:image" content="{og}">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{e(title)}">
  <meta name="twitter:description" content="{e(desc)}">
  <meta name="twitter:image" content="{og}">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="preconnect" href="https://images.unsplash.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Archivo:wght@700;800&amp;family=Public+Sans:wght@400;500;600&amp;family=Source+Serif+4:ital,wght@1,400;1,500&amp;display=swap">

  {EARLY}

{blocks}

  <style>
    {css_region()}
  </style>
</head>
"""


def faq_schema(faq):
    return {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": a}}
            for q, a in faq
        ],
    }


def breadcrumbs_schema(items):
    return {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": n, "item": SITE + u}
            for i, (n, u) in enumerate(items)
        ],
    }


def crumbs_html(items):
    lis = []
    for i, (name, url) in enumerate(items):
        if i == len(items) - 1:
            lis.append(f'<li aria-current="page">{e(name)}</li>')
        else:
            lis.append(f'<li><a href="{e(url)}">{e(name)}</a></li>')
    return f'<nav class="crumbs" aria-label="Breadcrumb"><ol>{"".join(lis)}</ol></nav>'


def trust_strip():
    return """    <div class="trust on-dark" role="region" aria-label="Why homeowners trust us">
      <div class="wrap">
        <ul>
          <li>Licensed &amp; insured</li>
          <li>WSIB covered</li>
          <li>Written fixed-price quotes</li>
          <li>Call any time, 24/7</li>
          <li>[X]-year workmanship warranty</li>
        </ul>
      </div>
    </div>"""


def lead_form(fid, service=None, city=None):
    """Short single-step lead form. Service pages fix the service; city pages fix the city."""
    city_opts = "".join(f"<option>{c}</option>" for c in CITIES_ORDER) + "<option>Somewhere nearby</option>"
    if service:
        fixed = (f'<input type="hidden" name="service" value="{e(service)}">\n'
                 f'            <p class="lform__tag">{e(service)}</p>')
        choice = f"""<div class="field">
              <label for="{fid}-city">City</label>
              <select id="{fid}-city" name="city" required aria-describedby="{fid}-city-err">
                <option value="">Choose a city</option>{city_opts}
              </select>
              <p class="err" id="{fid}-city-err"></p>
            </div>"""
    else:
        fixed = (f'<input type="hidden" name="city" value="{e(city)}">\n'
                 f'            <p class="lform__tag">{e(city)}</p>')
        proj = "".join(f"<option>{e(s['name'])}</option>" for s in SERVICES)
        proj += f"<option>{EXTRA_WORK}</option><option>Not sure yet</option>"
        choice = f"""<div class="field">
              <label for="{fid}-project">Type of project</label>
              <select id="{fid}-project" name="project" required aria-describedby="{fid}-project-err">
                <option value="">Choose one</option>{proj}
              </select>
              <p class="err" id="{fid}-project-err"></p>
            </div>"""

    return f"""<div class="lhero__form" id="quote">
          <!-- Posts JSON to FORM_ENDPOINT in the shared script. Name and phone are the only required details. -->
          <form class="qform lform" id="{fid}" data-lead="short" data-done="{fid}-done" novalidate>
            <p class="lform__title">Get a free, fixed-price quote</p>
            <p class="lform__sub">Takes about a minute. A project lead calls you back to book a site visit.</p>
            {fixed}
            <div class="hp" aria-hidden="true">
              <label for="{fid}-hp">Leave this field empty</label>
              <input type="text" id="{fid}-hp" name="tb_hp_field" tabindex="-1" autocomplete="off">
            </div>
            <div class="field">
              <label for="{fid}-name">Name</label>
              <input id="{fid}-name" name="name" type="text" autocomplete="name" required aria-describedby="{fid}-name-err">
              <p class="err" id="{fid}-name-err"></p>
            </div>
            <div class="row-2">
              <div class="field">
                <label for="{fid}-phone">Phone</label>
                <input id="{fid}-phone" name="phone" type="tel" autocomplete="tel" inputmode="tel" required aria-describedby="{fid}-phone-err">
                <p class="err" id="{fid}-phone-err"></p>
              </div>
              <div class="field">
                <label for="{fid}-email">Email <span class="opt">(optional)</span></label>
                <input id="{fid}-email" name="email" type="email" autocomplete="email" aria-describedby="{fid}-email-err">
                <p class="err" id="{fid}-email-err"></p>
              </div>
            </div>
            {choice}
            <div class="field">
              <label for="{fid}-message">What are you planning? <span class="opt">(optional)</span></label>
              <textarea id="{fid}-message" name="message" rows="3" placeholder="Rough size, what's there now, when you'd like to start."></textarea>
            </div>
            <button class="btn btn--clay lform__submit" type="submit">Get my free quote</button>
            <div class="qstatus qstatus--error" role="alert" hidden></div>
            <p class="qfine">No obligation. We reply within [X] hours, or call {PHONE} any time. Your details are only used for this quote.</p>
          </form>

          <div class="qform qdone" id="{fid}-done" tabindex="-1" hidden>
            <div class="qdone__mark" aria-hidden="true">
              <svg viewBox="0 0 16 16"><path d="M2 8.5l4 4 8-9" fill="none" stroke="currentColor" stroke-width="2"/></svg>
            </div>
            <h2 class="lform__title">Got it. Thanks.</h2>
            <p>Here's what happens next:</p>
            <ol>
              <li>A project lead calls you, usually within [X] hours.</li>
              <li>We book a site visit at a time that suits you.</li>
              <li>You get a written, fixed-price quote with HST shown.</li>
            </ol>
            <p>In a hurry? Call <a href="{TEL}">{PHONE}</a>. We pick up any time, 24/7.</p>
          </div>
        </div>"""


def landing_hero(page, fid, crumbs, eyebrow, service=None, city=None):
    pid, alt, note = page["hero"]
    hero_img = (f'<!-- REAL PHOTO: {e(note)} -->\n'
                f'      <img class="{{cls}}" src="{e(img_url(pid, 2000, 1200, 75))}"\n'
                f'           srcset="{e(img_url(pid, 900, 600, 70))} 900w, {e(img_url(pid, 1400, 840, 72))} 1400w, {e(img_url(pid, 2000, 1200, 75))} 2000w"\n'
                f'           sizes="100vw" width="2000" height="1200" alt="{e(alt)}" fetchpriority="high" decoding="async">')
    ticks = "".join(f"<li>{e(t)}</li>" for t in page["ticks"])
    copy = f"""<div class="lhero__copy">
          {crumbs_html(crumbs)}
          <p class="eyebrow">{e(eyebrow)}</p>
          <h1 id="page-title">{e(page["h1"])}</h1>
          <p class="lhero__sub">{e(page["sub"])}</p>
          <ul class="ticks">{ticks}</ul>
          <p class="lhero__call">Rather talk it through? Call <a href="{TEL}">{PHONE}</a>. Any time, 24/7.</p>
        </div>"""
    form = lead_form(fid, service=service, city=city)
    if page["variant"] == "photo":
        return f"""    <section class="lhero lhero--photo" aria-labelledby="page-title">
      {hero_img.replace("{cls}", "lhero__img")}
      <div class="wrap lhero__grid">
        {copy}
        {form}
      </div>
    </section>
{trust_strip()}"""
    return f"""    <section class="lhero lhero--split" aria-labelledby="page-title">
      <div class="wrap lhero__grid">
        {copy}
        {form}
      </div>
    </section>
    <div class="lband-wrap">
      <div class="wrap">
        <figure class="lband ph">
          {hero_img.replace("{cls}", "lband__img")}
        </figure>
      </div>
    </div>
{trust_strip()}"""


def section_head(eyebrow, h2, lede, hid):
    return f"""        <div class="section-head reveal">
          <div>
            <p class="eyebrow">{e(eyebrow)}</p>
            <h2 id="{hid}">{e(h2)}</h2>
          </div>
          <p class="lede">{e(lede)}</p>
        </div>"""


def faq_section(faq, h2, prefix, bg=""):
    items = []
    for i, (q, a) in enumerate(faq, 1):
        items.append(f"""          <div class="acc__item">
            <h3><button class="acc__btn" type="button" aria-expanded="false" aria-controls="{prefix}-a{i}" id="{prefix}-q{i}">{e(q)}<span class="acc__icon" aria-hidden="true"></span></button></h3>
            <div class="acc__panel" id="{prefix}-a{i}" role="region" aria-labelledby="{prefix}-q{i}"><div><p>{e(a)}</p></div></div>
          </div>""")
    return f"""    <section class="section {bg}" id="faq" aria-labelledby="faq-title">
      <div class="wrap faq">
        <div class="faq__head reveal">
          <p class="eyebrow">FAQ</p>
          <h2 id="faq-title">{e(h2)}</h2>
          <p class="lede">Don't see yours? Call {PHONE}. Someone picks up any time, 24/7.</p>
        </div>
        <div class="acc reveal">
{chr(10).join(items)}
        </div>
      </div>
    </section>"""


def cta_band(h2, p):
    return f"""    <section class="cta-band on-dark" aria-labelledby="cta-title">
      <div class="wrap cta-band__grid reveal">
        <div>
          <h2 id="cta-title">{e(h2)}</h2>
          <p>{e(p)}</p>
        </div>
        <div class="cta-band__btns">
          <a class="btn btn--clay" href="#quote">Get a Free Quote</a>
          <a class="btn btn--ghost-light" href="{TEL}">Call {PHONE}</a>
        </div>
      </div>
    </section>"""


def page_shell(head_html, path, main_html):
    return f"""{head_html}
<body>
  {header(current=path)}

  <main id="main">
{main_html}
  </main>

  {footer()}

  {js_region()}
</body>
</html>
"""


# ======================================================================
# Service page
# ======================================================================

def service_page(s):
    path = "/" + s["slug"]
    crumbs = [("Home", "/"), ("Services", "/#services"), (s["name"], path)]
    schema = [
        {
            "@context": "https://schema.org",
            "@type": "Service",
            "name": s["name"],
            "serviceType": s["name"],
            "description": s["desc"],
            "url": SITE + path,
            "provider": BUSINESS,
            "areaServed": [{"@type": "City", "name": c} for c in CITIES_ORDER],
        },
        breadcrumbs_schema(crumbs),
        faq_schema(s["faq"]),
    ]
    fid = "lead-" + s["slug"]

    scope = "\n".join(
        f"""          <li class="scope__group">
            <h3>{e(t)}</h3>
            <ul class="inc">{"".join(f"<li>{e(i)}</li>" for i in items)}</ul>
          </li>""" for t, items in s["scope"])

    pair = []
    for pid, alt, cap, note in s["pair"]:
        pair.append(f"""          <figure class="reveal">
            <!-- REAL PHOTO: {e(note)} -->
            <div class="pair__img ph"><img src="{e(img_url(pid, 1100))}" width="1100" height="733" loading="lazy" decoding="async" alt="{e(alt)}"></div>
            <figcaption>{e(cap)}</figcaption>
          </figure>""")

    method = "\n".join(
        f'          <li class="reveal"><h3>{e(t)}</h3><p>{e(d)}</p></li>' for t, d in s["method"])

    compare_html = ""
    if s.get("compare"):
        c = s["compare"]
        thead = "".join(f'<th scope="col">{e(x)}</th>' for x in c["cols"])
        rows = "".join(
            f'<tr><th scope="row">{e(r)}</th>{"".join(f"<td>{e(v)}</td>" for v in vals)}</tr>'
            for r, vals in c["rows"])
        compare_html = f"""
    <section class="section" id="compare" aria-labelledby="compare-title">
      <div class="wrap">
{section_head("Compare", "Hardwood, engineered, LVP or tile: which floor goes where", "The short version of what we explain at every site visit. Scroll sideways on a phone.", "compare-title")}
        <div class="table-scroll reveal" role="region" aria-label="Flooring comparison table" tabindex="0">
          <table class="compare compare--wide">
            <caption class="sr-only">Comparison of flooring types</caption>
            <thead><tr><th scope="col"><span class="sr-only">Property</span></th>{thead}</tr></thead>
            <tbody>{rows}</tbody>
          </table>
        </div>
      </div>
    </section>"""

    drivers = "".join(f"<li><strong>{e(t)}</strong><span>{e(d)}</span></li>" for t, d in s["drivers"])
    trows = "".join(
        f'<tr><th scope="row">{e(a)}</th><td>{e(b)}</td><td>{e(c)}</td></tr>' for a, b, c in s["table"])

    local = []
    for city in CITIES_ORDER:
        slug = city.lower()
        local.append(f"""          <article class="area reveal">
            <div class="area__top"><h3>{city}</h3></div>
            <p>{e(s["local"][city])}</p>
            <a class="arrow-link" href="/{slug}">General contractor in {city}
              {ARROW}</a>
          </article>""")

    related = "\n".join(
        f'          <li><a href="/{o["slug"]}">{e(o["name"])}{ARROW}</a></li>'
        for o in SERVICES if o["slug"] != s["slug"])

    main = f"""{landing_hero(s, fid, crumbs, "Service", service=s["name"])}

    <section class="section" id="scope" aria-labelledby="scope-title">
      <div class="wrap">
        <div class="split-head reveal">
          <div>
            <p class="eyebrow">What's included</p>
            <h2 id="scope-title">{e(s["intro_h2"])}</h2>
          </div>
          <div class="split-head__body">
            {"".join(f"<p>{e(p)}</p>" for p in s["intro"])}
          </div>
        </div>
        <ul class="scope">
{scope}
        </ul>
        <div class="pair">
{chr(10).join(pair)}
        </div>
      </div>
    </section>
{compare_html}
    <section class="section bg-limestone" id="method" aria-labelledby="method-title">
      <div class="wrap">
{section_head("How we build it", s["method_h2"], s["method_lede"], "method-title")}
        <ol class="method">
{method}
        </ol>
      </div>
    </section>

    <section class="section" id="cost" aria-labelledby="cost-title">
      <div class="wrap price">
        <div class="reveal">
          <p class="eyebrow">Cost</p>
          <h2 id="cost-title">{e(s["price_h2"])}</h2>
          <p class="lede">{e(s["price_intro"])}</p>
          <ul class="drivers">{drivers}</ul>
        </div>
        <div class="reveal">
          <div class="table-scroll" role="region" aria-label="Planning price ranges" tabindex="0">
            <table class="compare compare--wide">
              <caption>Planning ranges</caption>
              <thead><tr><th scope="col">Typical scope</th><th scope="col">Price range</th><th scope="col">Time on site</th></tr></thead>
              <tbody>{trows}</tbody>
            </table>
          </div>
          <p class="price__note">Ranges are for planning only. Your quote is a fixed price for your house, with HST shown as its own line.</p>
          <p><a class="arrow-link" href="#quote">Get your fixed price {ARROW}</a></p>
        </div>
      </div>
    </section>

    <section class="section bg-limestone" id="areas" aria-labelledby="areas-title">
      <div class="wrap">
{section_head("Where we work", s["name"] + " in Mississauga, Oakville, Burlington and Hamilton", "The same crew and the same fixed-price quote in all four cities. Here's what we see most in each.", "areas-title")}
        <div class="areas">
{chr(10).join(local)}
        </div>
      </div>
    </section>

{faq_section(s["faq"], s["name"] + " questions", "faq")}

{cta_band(s["cta_h2"], s["cta_p"])}

    <section class="section" id="related" aria-labelledby="related-title">
      <div class="wrap">
{section_head("More services", "Other work we do", "Most jobs turn into two. We quote each one on its own line.", "related-title")}
        <ul class="related reveal">
{related}
        </ul>
      </div>
    </section>"""

    return page_shell(head(s["title"], s["desc"], path, s["hero"][0], schema), path, main)


# ======================================================================
# City page
# ======================================================================

def city_page(c):
    path = "/" + c["slug"]
    crumbs = [("Home", "/"), ("Areas", "/#areas"), (c["name"], path)]
    schema = [
        {
            "@context": "https://schema.org",
            "@type": "Service",
            "name": f"General contracting in {c['name']}",
            "serviceType": "General contractor",
            "description": c["desc"],
            "url": SITE + path,
            "provider": BUSINESS,
            "areaServed": {"@type": "City", "name": c["name"]},
        },
        breadcrumbs_schema(crumbs),
        faq_schema(c["faq"]),
    ]
    fid = "lead-" + c["slug"]

    hoods = "".join(f"<li><h3>{e(n)}</h3><p>{e(t)}</p></li>" for n, t in c["hoods"])

    rows = []
    for i, s in enumerate(SERVICES, 1):
        rows.append(f"""          <li class="reveal">
            <span class="svc-rows__n">{i:02d}</span>
            <h3>{e(s["name"])}</h3>
            <p>{e(s["local"][c["name"]])}</p>
            <a class="arrow-link" href="/{s["slug"]}">Learn more<span class="sr-only"> about {e(s["name"].lower())}</span> {ARROW}</a>
          </li>""")

    steps = []
    for i, (t, d, get) in enumerate(PROCESS, 1):
        steps.append(f"""          <li class="step reveal">
            <span class="step__n" aria-hidden="true">{i:02d}</span>
            <h3>{e(t)}</h3>
            <p>{e(d)}</p>
            <p class="step__get"><strong>You get:</strong> {e(get)}</p>
          </li>""")

    others = "\n".join(
        f'          <li><a href="/{o["slug"]}">General contractor in {e(o["name"])}{ARROW}</a></li>'
        for o in CITIES if o["slug"] != c["slug"])

    main = f"""{landing_hero(c, fid, crumbs, "Service area", city=c["name"])}

    <section class="section" id="about" aria-labelledby="about-title">
      <div class="wrap">
        <div class="split-head reveal">
          <div>
            <p class="eyebrow">{e(c["name"])}</p>
            <h2 id="about-title">{e(c["intro_h2"])}</h2>
          </div>
          <div class="split-head__body">
            {"".join(f"<p>{e(p)}</p>" for p in c["intro"])}
          </div>
        </div>
        <ul class="hoods reveal">{hoods}</ul>
      </div>
    </section>

    <section class="section bg-limestone" id="services" aria-labelledby="services-title">
      <div class="wrap">
{section_head("Services", "Renovation services in " + c["name"], "Six kinds of work make up most of our calendar here. Each has its own page with the details.", "services-title")}
        <ol class="svc-rows">
{chr(10).join(rows)}
        </ol>
      </div>
    </section>

    <section class="section bg-ink on-dark" id="process" aria-labelledby="process-title">
      <div class="wrap">
{section_head("Process", "How a job runs in " + c["name"], "Four stages. You always know which one you're in and who to call about it.", "process-title")}
        <ol class="steps">
{chr(10).join(steps)}
        </ol>
      </div>
    </section>

{faq_section(c["faq"], "Questions from " + c["name"] + " homeowners", "faq")}

{cta_band("Book a site visit in " + c["name"], "One visit, then a written fixed price with HST shown. Call any time, 24/7.")}

    <section class="section" id="related" aria-labelledby="related-title">
      <div class="wrap">
{section_head("Other areas", "We also work in", "Same crew, same fixed-price quotes.", "related-title")}
        <ul class="related reveal">
{others}
        </ul>
      </div>
    </section>"""

    return page_shell(head(c["title"], c["desc"], path, c["hero"][0], schema), path, main)


# ======================================================================
# Homepage patching, sitemap, lint
# ======================================================================

def replace_region(text, start, end, new):
    pat = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
    if not pat.search(text):
        sys.exit(f"Marker {start!r} not found in index.html")
    return pat.sub(lambda m: new, text, count=1)


def patch_home():
    p = ROOT / "index.html"
    t = p.read_text()
    t = replace_region(t, "<!-- @build:early -->", "<!-- @end:early -->", EARLY)
    t = replace_region(t, "/* @build:css", "/* @end:css */", css_region())
    t = replace_region(t, "<!-- @build:header", "<!-- @end:header -->", header(home=True))
    t = replace_region(t, "<!-- @build:footer", "<!-- @end:footer -->", footer(home=True))
    t = replace_region(t, "<!-- @build:js", "<!-- @end:js -->", js_region())
    p.write_text(t)
    return t


def lint(name, text):
    problems = []
    visible = re.sub(r"<style.*?</style>|<script(?! type=\"application/ld\+json\").*?</script>", "", text, flags=re.S)
    low = visible.lower()
    for w in BANNED:
        if w in low:
            problems.append(f"banned word '{w}'")
    for ch, label in (("—", "em dash"), ("–", "en dash")):
        if ch in text:
            problems.append(label)
    h1 = len(re.findall(r"<h1[\s>]", text))
    if h1 != 1:
        problems.append(f"{h1} H1 elements")
    m = re.search(r'<meta name="description" content="([^"]*)"', text)
    if m:
        n = len(html.unescape(m.group(1)))
        if not 150 <= n <= 160:
            problems.append(f"meta description is {n} characters (want 150 to 160)")
    ids = re.findall(r'\sid="([^"]+)"', text)
    dup = {i for i in ids if ids.count(i) > 1}
    if dup:
        problems.append(f"duplicate ids {sorted(dup)}")
    for p in problems:
        print(f"  LINT {name}: {p}")
    return not problems


def main():
    pages = {}
    for s in SERVICES:
        pages[s["slug"]] = service_page(s)
    for c in CITIES:
        pages[c["slug"]] = city_page(c)

    ok = True
    for slug, text in pages.items():
        out = ROOT / f"{slug}.html"
        out.write_text(text)
        ok &= lint(slug, text)
        print(f"wrote {slug}.html ({len(text) // 1024} KB)")

    home = patch_home()
    ok &= lint("index", home)
    print("patched index.html")

    today = datetime.date.today().isoformat()
    urls = [SITE + "/"] + [f"{SITE}/{slug}" for slug in pages]
    (ROOT / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "".join(f"  <url><loc>{u}</loc><lastmod>{today}</lastmod></url>\n" for u in urls)
        + "</urlset>\n")
    (ROOT / "robots.txt").write_text(f"User-agent: *\nAllow: /\n\nSitemap: {SITE}/sitemap.xml\n")
    print("wrote sitemap.xml and robots.txt")
    if not ok:
        sys.exit(1)


if __name__ == "__main__":
    main()
