"""
Page copy for the TrustBuildGTA service and city landing pages.

Rules for anyone editing this file (the build script lints for most of them):
- No em or en dashes. No emoji. Canadian spelling.
- Never invent prices, reviews, stats, timelines or licence numbers. Write around them
  ("your quote gives you a start and finish date") instead of using placeholders.
- Banned words are listed in build.py (BANNED). Keep the voice plain and specific.
"""

CITIES_ORDER = ["Mississauga", "Oakville", "Burlington", "Hamilton"]

# Unsplash IDs are temporary placeholders. Each image has a note describing the real photo to swap in.
SERVICES = [
    # ------------------------------------------------------------------ BASEMENT
    {
        "slug": "basement-renovation",
        "name": "Basement renovation",
        "variant": "photo",
        "title": "Basement Renovation Mississauga, Oakville, Burlington & Hamilton | TrustBuildGTA",
        "desc": "Basement finishing and renovation in Mississauga, Oakville, Burlington and Hamilton. Membrane, ROCKWOOL insulation and permits in one fixed-price quote.",
        "h1": "Basement Renovation in Mississauga, Oakville, Burlington & Hamilton",
        "sub": "Finished basements built on a proper envelope, so the room stays dry and holds its heat. Membrane, insulation, permits and inspections are all in one fixed-price quote.",
        "ticks": ["Written fixed-price quote, HST shown", "Permits and inspections handled", "Legal second suites built to the Ontario Building Code"],
        "hero": ("1600566753190-17f0baa2a6c3", "Finished basement rec room with LVP flooring and pot lights",
                 "wide shot of a finished TrustBuildGTA basement, lights on, no people"),
        "intro_h2": "A basement is only as good as what's behind the drywall",
        "intro": [
            "Most basements in Peel, Halton and Hamilton were poured with no insulation on the walls and a slab sitting straight on gravel. Frame and drywall over that and you get a musty room with cold floors by February. We deal with the concrete first, then build the room.",
            "Before we price anything, we check the foundation for moisture, look at the sump and the grading outside, and confirm your panel can take the new circuits. If there's a water problem, you hear about it at the site visit, not after the drywall is up.",
        ],
        "scope": [
            ("Envelope", ["DMX or Delta-FL dimpled membrane on foundation walls", "Stud walls held off the concrete", "ROCKWOOL batts and vapour control where code calls for it", "Insulated subfloor panels over the slab"]),
            ("Mechanical", ["New circuits, pot lights and a subpanel if needed", "Heating and return air extended to every room", "Rough-in for a bathroom, wet bar or laundry", "Egress windows cut and installed"]),
            ("Finishes", ["Drywall, tape and paint", "LVP, engineered or tile flooring", "Doors, trim and baseboard", "Bathroom tile over Schluter waterproofing"]),
            ("Second suites", ["Fire separation between units", "Interconnected smoke and CO alarms", "Separate entrance where the layout allows", "Permit drawings and inspections"]),
        ],
        "pair": [
            ("1600210492486-724fe5c67fb0", "Basement rec room in Meadowvale finished with LVP and pot lights", "Meadowvale, Mississauga. Open rec room with a three-piece bathroom.", "finished rec room, landscape"),
            ("1513694203232-719a280e022f", "Media wall and built-in shelving in a Stoney Creek basement", "Stoney Creek, Hamilton. Media wall built around the existing ductwork.", "media wall or built-ins, portrait or square"),
        ],
        "method_h2": "How we finish a basement, in order",
        "method_lede": "Six stages. Inspections happen between them, so nothing gets closed in before the city has seen it.",
        "method": [
            ("Moisture check and measure", "We look for efflorescence and damp spots, check grading and downspouts outside, and measure every wall and ceiling height. Low spots under ductwork get flagged now."),
            ("Drawings and permit", "Layout drawings go to you first, then to the city if a permit is needed. Permit review times vary by city and season, and we build that into the start date."),
            ("Envelope", "Membrane on the walls, framing held off the concrete, subfloor over the slab. You never see this part, and it matters most."),
            ("Rough-in and inspection", "Electrical, plumbing and ductwork go in, and the inspector sees all of it before any wall is closed."),
            ("Insulation, drywall and finishes", "ROCKWOOL and vapour control, drywall, then flooring, trim and paint."),
            ("Final inspection and walkthrough", "The permit gets closed, you get the paperwork, and we walk the space with you before the final invoice."),
        ],
        "price_h2": "What a basement renovation costs",
        "price_intro": "We don't quote by the square foot over the phone, because two basements the same size can be far apart in price. These are the things that move the number.",
        "drivers": [
            ("Water", "An active leak or damp wall has to be fixed, from outside or with interior drainage, before finishing."),
            ("Ceiling height", "Ductwork and beams that need boxing in, or a floor that needs lowering, add labour."),
            ("A bathroom", "Breaking the slab for drains is the biggest single line in most basement quotes."),
            ("A second suite", "Fire separation, egress, a separate entrance and permit drawings add cost. They also add rent."),
            ("Finish level", "LVP or engineered, hollow or solid-core doors, a wet bar or not."),
        ],
        "local": {
            "Mississauga": "Meadowvale and Erin Mills townhouses and semis make up a lot of our basement work, and many of them become legal second suites.",
            "Oakville": "Glen Abbey and Joshua Creek basements are usually big, open and unfinished, which makes them good candidates for a rec room with a full bathroom.",
            "Burlington": "Aldershot bungalows often need ceiling height worked out around ductwork before the finishing starts.",
            "Hamilton": "Older homes in Westdale and Dundas usually need waterproofing first, and sometimes underpinning to get a usable ceiling.",
        },
        "faq": [
            ("Do I need a permit to finish my basement?", "Yes, if you are adding a bathroom, a bedroom or a second unit, or moving walls or plumbing. A plain finish with no new plumbing may not need one, but the rules vary by city, so we check with the building department for your address before we quote. When a permit is needed, we handle the drawings, the application and the inspections."),
            ("How long does a basement renovation take?", "It depends on the size, a bathroom and the permit. An open rec room is a shorter job than a legal second suite, which has more inspections. Your quote gives you a start date and a finish date in writing, with the inspections already built in."),
            ("Can you turn my basement into a legal second suite?", "In most cases, yes. Ontario allows a second unit in most detached houses, semis and townhouses, subject to the Ontario Building Code and your city's zoning rules. It needs fire separation, egress windows, interconnected alarms and a permit. We confirm your address qualifies before you spend anything on drawings."),
            ("What flooring is best for a basement?", "LVP, in most cases. It is waterproof and floats over a subfloor or membrane on the slab. Engineered hardwood can work over a dry slab with a proper subfloor, but solid hardwood should not go below grade."),
        ],
        "cta_h2": "Find out what your basement will cost",
        "cta_p": "One site visit, then a written fixed price with HST shown. No per-square-foot guesses.",
    },
    # ------------------------------------------------------------------ KITCHEN
    {
        "slug": "kitchen-renovation",
        "name": "Kitchen renovation",
        "variant": "split",
        "title": "Kitchen Renovation Mississauga, Oakville, Burlington & Hamilton | TrustBuildGTA",
        "desc": "Kitchen renovation in Mississauga, Oakville, Burlington and Hamilton. New layouts, cabinets, quartz and porcelain counters, one project lead and a fixed price.",
        "h1": "Kitchen Renovation in Mississauga, Oakville, Burlington & Hamilton",
        "sub": "New layouts, cabinets and slab counters, built in the right order by one crew. You get a fixed price and a finish date before we pull the first cabinet off the wall.",
        "ticks": ["Written fixed-price quote, HST shown", "Layout drawings before you sign", "Soft-close hardware as standard"],
        "hero": ("1556911220-bff31c812dba", "Renovated kitchen with white quartz counters and soft-close shaker cabinets",
                 "finished TrustBuildGTA kitchen, wide landscape, shot from the doorway"),
        "intro_h2": "Most kitchen delays come from bad sequencing",
        "intro": [
            "A kitchen involves more trades than any other room: demolition, plumbing, electrical, drywall, cabinets, counters, tile and paint. When one of them shows up early or late, the whole job stalls. Your project lead books every trade in order and is on site when they arrive.",
            "We order cabinets the week you sign the design, since they have the longest lead time. Quartz or porcelain slab counters are templated after the cabinets are installed and level, never from drawings.",
        ],
        "scope": [
            ("Layout and structure", ["Wall removal with an engineered beam and a permit", "Island and peninsula layouts", "Moving the sink, range or fridge", "Bulkhead removal where ducts allow"]),
            ("Mechanical", ["Dedicated circuits for range, dishwasher and microwave", "Under-cabinet and pot lighting", "Range hood vented outside", "Gas line moves by a licensed fitter"]),
            ("Cabinets and counters", ["Stock, semi-custom or custom cabinetry", "Soft-close hinges and drawer slides", "Quartz or porcelain slab counters", "Undermount sinks and new faucets"]),
            ("Finishes", ["Tile backsplash", "Flooring carried into adjoining rooms", "Drywall repair and paint", "Trim, crown and filler panels"]),
        ],
        "pair": [
            ("1484154218962-a197022b5858", "White kitchen in Glen Abbey with quartz counters and a tiled backsplash", "Glen Abbey, Oakville. Same footprint, new cabinets, quartz and lighting.", "finished kitchen, landscape"),
            ("1565538810643-b5bdb714032a", "Galley kitchen in Streetsville with open shelving and soft-close drawers", "Streetsville, Mississauga. Galley kitchen with open shelving.", "detail shot of cabinets or counters, portrait"),
        ],
        "method_h2": "How a kitchen renovation runs",
        "method_lede": "The order matters more than the speed. This is the order we hold to.",
        "method": [
            ("Measure and design", "We measure the room, check where plumbing and ducts can move, and draw a layout with you. Cabinet and finish selections happen here."),
            ("Order and schedule", "Cabinets go on order the week you sign. The start date is set around their delivery, so your kitchen isn't torn out and sitting empty."),
            ("Demolition and rough-in", "Old kitchen out, floors protected, dust walls up. Plumbing and electrical move, and the inspector signs off if a permit applies."),
            ("Cabinets, then counters", "Cabinets are installed and levelled, then counters are templated from the real boxes. Fabrication time is already built into your schedule."),
            ("Backsplash and finishes", "Sink and appliances hooked up, backsplash tiled, paint and trim finished."),
            ("Walkthrough", "We go drawer by drawer with you and fix anything that's off before the final payment."),
        ],
        "price_h2": "What a kitchen renovation costs",
        "price_intro": "Cabinets and counters are usually more than half the price. After that, it comes down to how much of the room moves.",
        "drivers": [
            ("Layout changes", "Keeping the sink and range where they are saves plumbing, venting and electrical."),
            ("Walls", "Taking out a load-bearing wall means an engineer, a beam and a permit."),
            ("Cabinet grade", "Stock, semi-custom and custom cabinets can differ by a wide margin for the same layout."),
            ("Counters", "Quartz and porcelain are priced by the slab, so a large island can mean an extra slab."),
            ("Flooring", "Running new flooring through the main floor avoids a seam but adds square footage."),
        ],
        "local": {
            "Mississauga": "Lorne Park and Port Credit kitchens tend to be full renovations, often with a wall coming down to the dining room.",
            "Oakville": "Glen Abbey and Joshua Creek homes from the eighties and nineties are due for their first real kitchen.",
            "Burlington": "Millcroft and Alton Village kitchens are usually refreshes: same layout, better cabinets and quartz.",
            "Hamilton": "Ancaster kitchens run larger, and century homes in Westdale often need wiring brought up to date first.",
        },
        "faq": [
            ("How long does a kitchen renovation take?", "It depends on how much of the room moves. Keeping the layout is quicker than moving walls or plumbing. Cabinets have the longest lead time, so we order them the week you sign, and counters are templated after the cabinets go in. Your quote gives you a start date and a finish date in writing."),
            ("Can I live at home during a kitchen renovation?", "Yes, most of our clients do. We set up dust walls and floor protection, and help you plan a temporary kitchen in another room with the fridge and a microwave."),
            ("Should I choose quartz or porcelain counters?", "Quartz is the safe default: consistent, hard to stain and easy to seam. Porcelain slab is thinner, handles heat better and suits a modern look, but it is harder to fabricate and can chip at the edge if hit hard. We show you both before you pick."),
            ("Do I need a permit for a kitchen renovation?", "Not for new cabinets, counters and finishes. You do need one to remove or alter a load-bearing wall, and for significant plumbing changes. We tell you at the site visit and handle the application if one is needed."),
        ],
        "cta_h2": "Get a fixed price on your kitchen",
        "cta_p": "We measure, draw the layout with you and price every line. You see the finish date before you sign.",
    },
    # ------------------------------------------------------------------ BATHROOM
    {
        "slug": "bathroom-renovation",
        "name": "Bathroom renovation",
        "variant": "split",
        "title": "Bathroom Renovation Mississauga, Oakville, Burlington & Hamilton | TrustBuildGTA",
        "desc": "Bathroom renovation in Mississauga, Oakville, Burlington and Hamilton. Showers waterproofed with Schluter-KERDI and DITRA, flood tested, at a fixed price.",
        "h1": "Bathroom Renovation in Mississauga, Oakville, Burlington & Hamilton",
        "sub": "Showers and ensuites waterproofed with Schluter-KERDI and DITRA, then tiled. A fixed price up front, and a flood test before any tile goes on.",
        "ticks": ["Written fixed-price quote, HST shown", "Schluter waterproofing on every shower", "Written workmanship warranty"],
        "hero": ("1552321554-5fefe8c9ef14", "Walk-in shower with large-format porcelain tile and a glass panel",
                 "finished TrustBuildGTA shower or ensuite, landscape, natural light"),
        "intro_h2": "The part of a bathroom that matters is the part you never see",
        "intro": [
            "Tile and grout are not waterproof. What keeps water out of your walls and subfloor is the membrane behind them. Every shower we build gets Schluter-KERDI on the walls, a KERDI tray or sloped mortar bed, and banded seams at every corner and valve.",
            "Floors get DITRA under the tile, which lets the tile and the subfloor move independently so grout lines don't crack. We flood-test shower pans for a day before tiling, and you are welcome to come and look.",
        ],
        "scope": [
            ("Demolition and rough-in", ["Gut to studs and subfloor", "New supply lines and shut-off valves", "Drain moves for new layouts", "Blocking for grab bars and glass"]),
            ("Waterproofing", ["Schluter-KERDI membrane on shower walls", "KERDI tray or sloped mortar bed", "DITRA uncoupling membrane under floor tile", "Flood test before any tile"]),
            ("Fixtures", ["Tub-to-shower conversions", "Curbless and linear-drain showers", "Vanities, toilets and faucets", "Glass panels and doors"]),
            ("Comfort", ["Electric heated floors on a thermostat", "Exhaust fan ducted outside, not into the attic", "Niches and benches", "Lighting and mirror circuits"]),
        ],
        "pair": [
            ("1584622650111-993a426fbf0a", "Ensuite in Millcroft with a floating vanity and porcelain wall tile", "Millcroft, Burlington. Corner tub out, walk-in shower in.", "finished vanity wall, landscape"),
            ("1620626011761-996317b8d101", "Main bathroom in a Westdale century home with a freestanding tub", "Westdale, Hamilton. Subfloor rebuilt before the new tile went down.", "shower niche or tile detail, portrait"),
        ],
        "method_h2": "How we build a bathroom that stays dry",
        "method_lede": "Waterproofing gets a full day of testing before tile. That day is in the schedule on purpose.",
        "method": [
            ("Measure and plan", "We check the subfloor, which way the joists run and where the drain can go. That decides if a curbless shower is possible."),
            ("Selections and quote", "Tile, fixtures and vanity picked and priced. Special-order items are ordered before demolition starts."),
            ("Demolition and rough-in", "Room gutted, plumbing and electrical moved, subfloor repaired or reinforced."),
            ("Waterproofing and flood test", "KERDI and DITRA installed, seams banded, and the shower pan flooded for a day."),
            ("Tile and fixtures", "Tile set and grouted, fixtures installed, glass measured once the tile is done."),
            ("Walkthrough", "We run every fixture with you and seal the grout before handing it over."),
        ],
        "price_h2": "What a bathroom renovation costs",
        "price_intro": "Size matters less than you'd think. Most of the cost is labour for waterproofing, tile and plumbing.",
        "drivers": [
            ("Moving plumbing", "Keeping the toilet and drain where they are saves a lot. Moving them on a slab or across joists does not."),
            ("Tile", "Large-format porcelain and detailed patterns take longer to set than a standard wall tile."),
            ("Shower type", "A curbless shower needs the floor recessed or built up, which adds framing time."),
            ("Glass", "Custom glass is measured after tile and priced by size and hardware."),
            ("Heated floors", "Electric floor heat adds a circuit and a thermostat, but little labour."),
        ],
        "local": {
            "Mississauga": "Townhouses in Meadowvale and Erin Mills often have a tub nobody uses, which makes them good tub-to-shower conversions.",
            "Oakville": "Ensuites in Glen Abbey and Joshua Creek are the most common job: the builder's corner tub comes out and a walk-in shower goes in.",
            "Burlington": "Millcroft and Alton Village bathrooms usually keep the layout and replace everything else.",
            "Hamilton": "Century homes in Westdale and Dundas often need the subfloor rebuilt before new tile can go down.",
        },
        "faq": [
            ("How long does a bathroom renovation take?", "A powder room is a short job and a full ensuite takes longer. The flood test and grout curing are built into the schedule, because rushing them is how showers fail. Your quote gives you a start date and a finish date in writing."),
            ("Can you convert my tub into a walk-in shower?", "Yes. It is one of the most common jobs we do. We check the drain location and floor structure first to see if a low curb or a curbless entry is possible."),
            ("What is Schluter-KERDI and why does it matter?", "KERDI is a waterproof sheet membrane that goes on shower walls and floors under the tile. It stops water from reaching the drywall and framing. Tile and grout on their own let water through."),
            ("Is a heated bathroom floor worth it?", "In a bathroom on a slab or over a garage, most people say yes. It is an electric mat under the tile on its own thermostat, and it adds little labour if you decide before the tile goes in."),
        ],
        "cta_h2": "Price out your bathroom",
        "cta_p": "Tell us what's there now and what you want. We'll visit, measure and give you a fixed price in writing.",
    },
    # ------------------------------------------------------------------ FLOORING
    {
        "slug": "flooring",
        "name": "Flooring installation",
        "variant": "photo",
        "title": "Flooring Installation Mississauga, Oakville, Burlington & Hamilton | TrustBuildGTA",
        "desc": "Hardwood, engineered, LVP and tile flooring installation in Mississauga, Oakville, Burlington and Hamilton. Subfloor levelled first, fixed-price quotes.",
        "h1": "Flooring Installation in Mississauga, Oakville, Burlington & Hamilton",
        "sub": "Hardwood, engineered, LVP and tile, installed over a subfloor we've levelled first. We'll tell you which one your rooms actually suit.",
        "ticks": ["Written fixed-price quote, HST shown", "Subfloor levelled before install", "Baseboard and transitions included"],
        "hero": ("1600607687939-ce8a6c25118c", "Open main floor with new wide-plank engineered hardwood",
                 "finished TrustBuildGTA main floor, low angle so the flooring reads, landscape"),
        "intro_h2": "Good floors start with a flat subfloor",
        "intro": [
            "Most squeaks, gaps and hollow spots come from what's under the floor, not the floor itself. Before anything goes down we check flatness with a straightedge, screw down loose subfloor and level the low spots.",
            "We install solid hardwood, engineered hardwood, luxury vinyl plank (LVP) and porcelain tile. We aren't tied to one supplier, so the recommendation is based on the room, not on what's in stock.",
        ],
        "scope": [
            ("Preparation", ["Removal and disposal of old flooring", "Subfloor screwed down and levelled", "Moisture testing on concrete", "Door jambs undercut"]),
            ("Installation", ["Solid and engineered hardwood, nailed, glued or floated", "LVP floated over underlay", "Porcelain and ceramic tile over DITRA", "Stair treads and nosing"]),
            ("Finishing", ["New baseboard and quarter round", "Transitions between rooms", "Touch-up paint on trim", "Furniture moved back"]),
            ("Materials", ["Supplied by us, or we install yours", "Samples brought to the site visit", "Spare boxes left for future repairs", "Manufacturer warranty paperwork"]),
        ],
        "pair": [
            ("1586023492125-27b2c045efd7", "Wide-plank engineered oak flooring through a Bronte living room", "Bronte, Oakville. Engineered oak through the whole main floor, no seams at doorways.", "finished hardwood room, landscape"),
            ("1600210492486-724fe5c67fb0", "LVP flooring in a finished Erin Mills basement", "Erin Mills, Mississauga. LVP over an insulated subfloor on the slab.", "LVP in a basement, portrait or square"),
        ],
        "compare": {
            "cols": ["Solid hardwood", "Engineered", "LVP", "Porcelain tile"],
            "rows": [
                ("Below grade", ["No", "Over a dry slab with subfloor", "Yes", "Yes"]),
                ("Water", ["Not waterproof", "Tolerates humidity, not puddles", "Waterproof core", "Waterproof"]),
                ("Refinishing", ["Many times", "If the wear layer allows", "No, replace the plank", "No"]),
                ("Underfoot", ["Warm, real wood", "Warm, real wood", "Warm, a little softer", "Cold without floor heat"]),
                ("Best spot", ["Main and upper floors", "Main floors, condos", "Basements, kitchens, laundry", "Bathrooms, entries"]),
            ],
        },
        "method_h2": "How we install a floor",
        "method_lede": "The install is the quick part. The prep before it decides how the floor feels in five years.",
        "method": [
            ("Measure and test", "Square footage measured room by room, and concrete tested for moisture if we're going below grade."),
            ("Choose the material", "Samples in your light, in your rooms. We explain the trade-offs so you only pick once."),
            ("Acclimatize", "Hardwood and engineered boxes sit in the house for the time the manufacturer specifies, so the boards adjust to its humidity before installation."),
            ("Prep the subfloor", "Old floor out, loose subfloor fixed, low spots levelled."),
            ("Install", "Boards or tile down with the right expansion gaps at walls and doorways."),
            ("Finish and clean up", "Baseboard, quarter round and transitions installed, site vacuumed, furniture back in place."),
        ],
        "price_h2": "What flooring installation costs",
        "price_intro": "Flooring is priced per square foot of material plus labour. The prep is what surprises people.",
        "drivers": [
            ("Material", "LVP, engineered and solid hardwood cover a wide range per square foot."),
            ("Subfloor work", "Levelling a sloped floor or replacing water-damaged subfloor adds labour."),
            ("Stairs", "Each stair is measured and cut on its own, and priced per step."),
            ("Removal", "Tearing out glued-down flooring or tile takes longer than carpet."),
            ("Pattern", "Herringbone and diagonal layouts take more time and more waste."),
        ],
        "local": {
            "Mississauga": "Streetsville and Port Credit homes often have original hardwood under the carpet, and sometimes it can be saved.",
            "Oakville": "Engineered hardwood through the main floor of Glen Abbey and Bronte homes is our most common Oakville flooring job.",
            "Burlington": "Millcroft and Alton Village homes usually swap builder carpet upstairs for engineered or LVP.",
            "Hamilton": "Older floors in Westdale and Dundas are often out of level, so the prep takes longer than the install.",
        },
        "faq": [
            ("Is LVP or hardwood better for a basement?", "LVP, in most basements. It is waterproof, it floats over the slab and it shrugs off the humidity swings that come with being below grade. Solid hardwood should not go on a concrete slab. Engineered hardwood can work over a dry slab with a proper subfloor if you want real wood underfoot, but it costs more and is less forgiving if water ever gets in."),
            ("Can engineered hardwood be refinished?", "Yes, if the wear layer is thick enough. A thick wear layer can be sanded and refinished more than once. A thin one may only take a light screen and recoat. We show you the wear layer spec on every product we quote."),
            ("Will you install flooring I bought myself?", "Yes. We check it on delivery for damage and quantity, and make sure there's enough extra to cover cuts. The material warranty stays between you and the supplier, and our workmanship warranty covers the installation."),
            ("How long does flooring installation take?", "Most main floors go down in a matter of days once the material has acclimatized. Stairs add time because each step is cut and fitted on its own. You get the schedule in writing with the quote."),
        ],
        "cta_h2": "Get a flooring quote with the prep included",
        "cta_p": "We bring samples to the site visit and check the subfloor while we're there, so the price you get is the real one.",
    },
    # ------------------------------------------------------------------ CONCRETE
    {
        "slug": "concrete-patios",
        "name": "Concrete patios and walkways",
        "variant": "photo",
        "title": "Concrete Patios & Walkways Mississauga, Oakville, Burlington & Hamilton | TrustBuildGTA",
        "desc": "Concrete patios, walkways and steps in Mississauga, Oakville, Burlington and Hamilton. Air-entrained concrete on a compacted base, built for freeze-thaw.",
        "h1": "Concrete Patios and Walkways in Mississauga, Oakville, Burlington & Hamilton",
        "sub": "Air-entrained concrete poured on a compacted granular base, so it survives Ontario freeze-thaw. Patios, walkways, steps and pads, at a fixed price.",
        "ticks": ["Written fixed-price quote, HST shown", "Air-entrained concrete on every pour", "Graded to shed water away from the house"],
        "hero": ("1600585154340-be6161a56a0c", "New concrete patio along the back of a detached house",
                 "finished TrustBuildGTA concrete patio, low evening light, landscape"),
        "intro_h2": "Concrete fails from the bottom up",
        "intro": [
            "Most cracked and heaved patios weren't poured badly. They were poured on a base that was never compacted, or on clay that holds water and lifts in winter. We dig out to undisturbed soil, lay Granular A in lifts and compact each one with a plate tamper before any forms go up.",
            "Every pour is air-entrained. The tiny air bubbles give freezing water somewhere to go, which is what stops the surface from flaking after a few winters of salt and freeze-thaw.",
        ],
        "scope": [
            ("Site prep", ["Excavation and haul-away", "Grading so water runs away from the house", "Granular A base compacted in lifts", "Forms set to slope"]),
            ("Concrete", ["Air-entrained mix from a ready-mix plant", "Wire mesh or rebar where loads call for it", "Control joints at the right spacing", "Proper curing, not a quick hose-down"]),
            ("Finishes", ["Broom finish for grip", "Smooth trowel with a tooled border", "Exposed aggregate", "Penetrating sealer"]),
            ("What we pour", ["Back patios and side walkways", "Front steps and landings", "Shed and hot tub pads", "Garden paths"]),
        ],
        "pair": [
            ("1600573472550-8090b5e0745e", "Broom-finished concrete walkway leading to the side door of a Port Credit semi", "Port Credit, Mississauga. Side walkway regraded to run water to the street.", "finished walkway, landscape"),
            ("1600047509807-ba8f99d2cdde", "Concrete patio with a tooled border behind a Bronte home", "Bronte, Oakville. Patio and step down to the lawn in one pour.", "finish or joint detail, portrait"),
        ],
        "method_h2": "How we pour a patio that lasts",
        "method_lede": "Half the work happens before the truck arrives. That's the half that decides if it lasts.",
        "method": [
            ("Site visit and layout", "We mark out the shape, check the grade with a level, and note downspouts and window wells that affect drainage."),
            ("Utility locates", "Locates are booked through Ontario One Call before any digging. It's free, and it's required."),
            ("Excavate and base", "Dig out to firm soil, lay Granular A and compact it in lifts."),
            ("Forms and pour", "Forms set with slope away from the house, reinforcement placed, concrete poured and finished."),
            ("Joints and cure", "Control joints cut, then the slab is kept damp and covered while it cures."),
            ("Seal and hand over", "Sealer once cured, and a care sheet about salt and snow removal."),
        ],
        "price_h2": "What a concrete patio costs",
        "price_intro": "Concrete is priced by area and thickness, but excavation and base are often half the work.",
        "drivers": [
            ("Access", "A backyard we can reach with a small machine costs less than one where everything goes in by wheelbarrow."),
            ("Removal", "Breaking out an old patio or interlock adds labour and disposal."),
            ("Finish", "Broom finish is standard. Exposed aggregate and borders add time."),
            ("Steps", "Formed steps take more labour per square foot than a flat slab."),
            ("Grading", "A yard that slopes toward the house needs more fill, or a step down."),
        ],
        "local": {
            "Mississauga": "Port Credit and Lorne Park lots have plenty of clay, so the base goes deeper there.",
            "Oakville": "Bronte backyards often want a patio and a walkway to the side gate done in one pour.",
            "Burlington": "Aldershot lots tend to be large, and pads for hot tubs and sheds are common.",
            "Hamilton": "On the Mountain and in Stoney Creek, grading away from the house is usually the first problem to solve.",
        },
        "faq": [
            ("Should I get a concrete patio or interlock?", "Poured concrete costs less up front and lasts for decades if it is air-entrained and placed on a properly compacted base. Interlock costs more, but single pavers can be lifted and relaid if the ground settles, and it does not crack the way a slab can. For a plain rectangle, concrete is good value. For curves, steps or soft ground, interlock is usually the better call."),
            ("How soon can I walk on a new concrete patio?", "Light foot traffic is usually fine after a day or two, and furniture after about a week. Concrete keeps gaining strength for around 28 days, so keep heavy loads off until then. We leave you a written care sheet with the dates for your pour."),
            ("Will my new concrete crack?", "Concrete shrinks as it cures, so some cracking is normal. Control joints decide where it cracks: in a straight line at the joint instead of across the slab. A compacted base and air-entrained concrete are what stop the heaving and flaking that ruin a patio."),
            ("Can I use salt on a new concrete patio?", "Not in the first winter. After that, avoid de-icers with ammonium nitrate or ammonium sulphate, which attack concrete. Sand for grip, or calcium chloride used sparingly, is safer."),
        ],
        "cta_h2": "Get a price on your patio or walkway",
        "cta_p": "We measure, check the grade and give you a fixed price that includes excavation, base and finish.",
    },
    # ------------------------------------------------------------------ BACKYARD
    {
        "slug": "backyard-landscaping",
        "name": "Backyard and landscaping builds",
        "variant": "split",
        "title": "Backyard Landscaping & Decks Mississauga, Oakville, Burlington & Hamilton | TrustBuildGTA",
        "desc": "Interlock patios, retaining walls, decks and fences in Mississauga, Oakville, Burlington and Hamilton. Footings below the frost line and deck permits handled.",
        "h1": "Backyard Landscaping and Decks in Mississauga, Oakville, Burlington & Hamilton",
        "sub": "Interlock patios, retaining walls, decks and fences, built with the drainage and footings the ground here needs. One crew, one fixed price.",
        "ticks": ["Written fixed-price quote, HST shown", "Deck footings below the frost line", "Deck permits drawn and filed"],
        "hero": ("1558036117-15d82a90b9b1", "Backyard with an interlock patio, planting beds and a low retaining wall",
                 "finished TrustBuildGTA backyard, wide, summer light"),
        "intro_h2": "Build for March, not for the photo",
        "intro": [
            "A backyard looks the same in July no matter how it was built. The difference shows up in March, when a deck on shallow footings has shifted and a retaining wall with no drainage has started to lean. We build for March.",
            "Deck footings go below the frost line, roughly 1.2 metres here. Retaining walls get clear stone and a perforated drain behind them. Interlock goes down on a compacted base with a screeded bedding layer and polymeric sand in the joints.",
        ],
        "scope": [
            ("Interlock", ["Patios, walkways and driveway borders", "Compacted base and screeded bedding", "Edge restraint and polymeric sand", "Relaying sunken pavers"]),
            ("Retaining walls", ["Segmental block walls", "Clear stone and drain pipe behind the wall", "Geogrid on taller walls", "Steps built into the wall"]),
            ("Decks", ["Pressure-treated or composite decking", "Helical piles or poured footings below frost", "Railings and stairs to code", "Permit drawings for attached decks"]),
            ("Fences and planting", ["Wood and aluminum fences", "Gates hung on proper posts", "Sod and planting beds", "Grading and drainage fixes"]),
        ],
        "pair": [
            ("1600047509807-ba8f99d2cdde", "Interlock patio and low retaining wall in an Ancaster backyard", "Ancaster, Hamilton. Retaining wall with drainage behind it, and interlock on the level.", "finished interlock or wall, landscape"),
            ("1600573472550-8090b5e0745e", "Pressure-treated deck with stairs down to the yard in Aldershot", "Aldershot, Burlington. Deck off the kitchen on footings below frost.", "finished deck, portrait"),
        ],
        "method_h2": "How a backyard build runs",
        "method_lede": "Drainage decides the order. Walls and bases go in before anything you'll see.",
        "method": [
            ("Walk the yard", "We look at grade, drainage, sun and access, and ask how you actually use the space."),
            ("Plan and permit", "A scaled plan with materials. Decks attached to the house or more than 60 cm above grade need a permit, and we file it."),
            ("Locates and dig", "Utility locates booked through Ontario One Call, then excavation for footings, bases and walls."),
            ("Structure", "Footings, deck framing and retaining walls, with drainage in place before backfill."),
            ("Surfaces", "Decking, interlock and railings installed."),
            ("Finish and clean up", "Sod, beds and final grading, and the site raked clean."),
        ],
        "price_h2": "What a backyard build costs",
        "price_intro": "Most yards are a mix of pieces. We price each piece on its own line, so you can phase the work over two seasons if you want to.",
        "drivers": [
            ("Access", "Tight side yards mean smaller machines and more hand work."),
            ("Materials", "Composite decking and premium pavers cost more than pressure-treated and standard interlock."),
            ("Wall height", "Retaining walls over about a metre need engineering and geogrid."),
            ("Soil", "Clay and fill need more excavation and base than sandy ground."),
            ("Permits", "Attached and raised decks need drawings and inspections."),
        ],
        "local": {
            "Mississauga": "Lorne Park and Erin Mills yards are big enough for a deck and a patio, and that's usually what people ask for.",
            "Oakville": "Bronte and Glen Abbey backyards often need the grading fixed before anything gets built.",
            "Burlington": "Aldershot and Millcroft lots suit a deck off the kitchen with steps down to interlock.",
            "Hamilton": "Ancaster and the Mountain have sloped lots where retaining walls do most of the work.",
        },
        "faq": [
            ("Do I need a permit to build a deck?", "In most of our cities you need one for a deck attached to the house, or any deck more than 60 cm above grade. We check your city's rules, draw the plans and book the inspections."),
            ("Pressure-treated or composite decking?", "Pressure-treated costs less and can be stained, but it needs maintenance every couple of years. Composite costs more up front, needs no staining and won't splinter. The framing underneath is pressure-treated either way."),
            ("Why is my interlock sinking?", "Almost always a base problem: not enough gravel, not compacted in lifts, or water getting underneath. We lift the pavers, fix the base and relay them, reusing the pavers if they're in good shape."),
            ("How deep do deck footings need to be?", "Below the frost line, which is roughly 1.2 metres in this part of Ontario. Shallower footings get lifted by frost and the deck goes out of level. We use poured footings or helical piles depending on access."),
        ],
        "cta_h2": "Plan your backyard with a fixed price",
        "cta_p": "We walk the yard with you, sort out the drainage and price each piece separately.",
    },
]

CITIES = [
    {
        "slug": "mississauga", "name": "Mississauga", "variant": "photo",
        "title": "General Contractor Mississauga | Basements, Kitchens & Baths | TrustBuildGTA",
        "desc": "Mississauga general contractor for basements, kitchens, bathrooms, flooring and concrete. Port Credit to Meadowvale. Fixed-price quotes, call any time 24/7.",
        "h1": "General Contractor in Mississauga",
        "sub": "Basements, kitchens, bathrooms, floors and backyards across Mississauga, from Port Credit to Meadowvale. Our office is on Matheson Blvd, so your project lead is never far away.",
        "ticks": ["Written fixed-price quote, HST shown", "Permits with the City of Mississauga handled", "Home base: 8 Matheson Blvd E"],
        "hero": ("1600047509807-ba8f99d2cdde", "Renovated detached home on a Mississauga street",
                 "a finished TrustBuildGTA project in Mississauga, exterior or main floor, landscape"),
        "intro_h2": "Mississauga is our home base",
        "intro": [
            "Most of our jobs are within twenty minutes of the office at 8 Matheson Blvd E. That matters more than it sounds: when an inspector gives a morning window or a delivery shows up early, someone can be there.",
            "The housing stock here is mostly detached homes, semis and townhouses from the seventies to the early 2000s. That means a lot of unfinished basements, original builder kitchens and bathrooms, and carpet on the second floor.",
        ],
        "hoods": [
            ("Port Credit", "Older detached homes and semis near the lake. Kitchens, flooring, and backyards with clay soil that needs a deeper base."),
            ("Streetsville", "Older homes mixed with newer infill. We often find original hardwood under the carpet here."),
            ("Erin Mills", "Townhouses and semis from the eighties and nineties, and a lot of basement second suites."),
            ("Lorne Park", "Larger lots and larger jobs: full kitchens with walls coming out, ensuites and backyard builds."),
            ("Meadowvale", "Townhouses and detached homes where the basement is the most common project."),
            ("Mississauga Valleys and Cooksville", "Homes from the sixties and seventies close to our office. Kitchens, bathrooms and basements with low ceilings to work around."),
        ],
        "faq": [
            ("Do I need a permit for a basement apartment in Mississauga?", "Yes. A second unit needs a building permit from the City of Mississauga and has to meet the Ontario Building Code and the city's zoning rules. We check that your property qualifies, prepare the drawings, apply for the permit and book the inspections."),
            ("How soon can you start a job in Mississauga?", "Call or send the form and we'll book a site visit at a time that suits you. Start dates depend on the season and on permits, and the date on your quote is the date we hold."),
            ("Do you also work in Brampton or Milton?", "Our main area is Mississauga, Oakville, Burlington and Hamilton. For jobs just outside it, call and ask. If we can't give your project proper attention, we'll tell you so."),
        ],
    },
    {
        "slug": "oakville", "name": "Oakville", "variant": "split",
        "title": "General Contractor Oakville | Kitchens, Ensuites & Basements | TrustBuildGTA",
        "desc": "Oakville general contractor for kitchens, ensuites, basements, flooring and backyards in Glen Abbey, Bronte and Joshua Creek. Written fixed-price quotes.",
        "h1": "General Contractor in Oakville",
        "sub": "Kitchens, ensuites, main floors and backyards in Glen Abbey, Bronte, Joshua Creek and the rest of Oakville. One project lead and a fixed price in writing.",
        "ticks": ["Written fixed-price quote, HST shown", "Permits with the Town of Oakville handled", "One project lead from start to finish"],
        "hero": ("1600573472550-8090b5e0745e", "Front walkway and entrance of a renovated Oakville home",
                 "a finished TrustBuildGTA project in Oakville, landscape"),
        "intro_h2": "Oakville homes ready for their first full renovation",
        "intro": [
            "Most of our Oakville work is kitchens, ensuites and main floors in homes built in the eighties and nineties. Those houses were well built but still have their original finishes, and they're due.",
            "It's a short drive down the QEW from our office, and we schedule Oakville jobs so a project lead is on site every working day.",
        ],
        "hoods": [
            ("Glen Abbey", "Two-storey homes from the eighties and nineties. Kitchens, ensuites and engineered hardwood through the main floor."),
            ("Bronte", "Near the lake, with older bungalows and newer builds side by side. Backyards, patios and full renovations."),
            ("Joshua Creek", "Larger homes from the nineties and 2000s. Ensuites, kitchens with islands and finished basements."),
            ("Old Oakville", "Older homes where plaster walls and old wiring change the scope of a kitchen or bathroom."),
            ("River Oaks", "Family homes where a basement rec room and a second bathroom are the usual asks."),
            ("West Oak Trails", "Newer homes with builder-grade finishes that owners are ready to replace."),
        ],
        "faq": [
            ("Do you handle building permits with the Town of Oakville?", "Yes. Where the Ontario Building Code calls for a permit, we prepare the drawings, apply to the Town of Oakville and book the inspections. The permit fee is shown on your quote."),
            ("Can you match the finishes in the rest of my house?", "Usually, yes. We bring samples to the site visit and match trim profiles, stain colours and flooring as closely as the products allow. If an exact match isn't possible, we'll suggest a clean break at a doorway instead."),
            ("How soon can you start a job in Oakville?", "Call or send the form and we'll book a site visit at a time that suits you. Start dates depend on the season and on permits, and the date on your quote is the date we hold."),
        ],
    },
    {
        "slug": "burlington", "name": "Burlington", "variant": "photo",
        "title": "General Contractor Burlington | Kitchens, Baths & Decks | TrustBuildGTA",
        "desc": "Burlington general contractor for kitchens, bathrooms, basements, flooring and decks in Aldershot, Millcroft and Alton Village. Fixed-price written quotes.",
        "h1": "General Contractor in Burlington",
        "sub": "Kitchen and bathroom upgrades, basements, floors and backyards across Burlington, from Aldershot to Alton Village. Written fixed price, one project lead.",
        "ticks": ["Written fixed-price quote, HST shown", "Permits with the City of Burlington handled", "Deck footings below the frost line"],
        "hero": ("1600585154340-be6161a56a0c", "Back of a renovated Burlington home with a new patio",
                 "a finished TrustBuildGTA project in Burlington, landscape"),
        "intro_h2": "A mix of work, because Burlington is a mix of houses",
        "intro": [
            "Burlington's housing runs from postwar bungalows near the lake to subdivisions built in the last twenty years. So the work is a mix too: kitchen and bath upgrades in Millcroft and Alton Village, basements and backyards in older areas like Aldershot.",
            "We cover all of Burlington, from the lake up to the escarpment.",
        ],
        "hoods": [
            ("Aldershot", "Older bungalows and side-splits. Basements, and backyards with room for a deck and a patio."),
            ("Millcroft", "Homes built around the golf course in the eighties and nineties. Kitchens and ensuites."),
            ("Alton Village", "Newer homes where builder-grade kitchens, bathrooms and carpet are ready to go."),
            ("Tyandaga", "Sloped lots and larger homes. Retaining walls and decks as often as kitchens."),
            ("Headon Forest", "Family homes where basement rec rooms and main bathrooms are common jobs."),
            ("Roseland", "Mature lots and older homes. Kitchens, additions and careful work around original features."),
        ],
        "faq": [
            ("Do you handle building permits with the City of Burlington?", "Yes. Where the Ontario Building Code calls for a permit, we prepare the drawings, apply to the City of Burlington and book the inspections. The permit fee is shown on your quote."),
            ("Do you build decks in Burlington?", "Yes. Decks attached to the house or more than 60 cm above grade need a permit, and we draw the plans and apply for it. Footings go below the frost line, roughly 1.2 metres down."),
            ("How soon can you start a job in Burlington?", "Call or send the form and we'll book a site visit at a time that suits you. Start dates depend on the season and on permits, and the date on your quote is the date we hold."),
        ],
    },
    {
        "slug": "hamilton", "name": "Hamilton", "variant": "split",
        "title": "General Contractor Hamilton | Basements, Waterproofing & Kitchens | TrustBuildGTA",
        "desc": "Hamilton general contractor for basement waterproofing and finishing, kitchens, bathrooms and patios in Westdale, Dundas, Ancaster and on the Mountain.",
        "h1": "General Contractor in Hamilton",
        "sub": "Basement waterproofing and finishing, kitchens, bathrooms and patios across Hamilton, from Westdale and Dundas to Ancaster, Stoney Creek and the Mountain.",
        "ticks": ["Written fixed-price quote, HST shown", "Permits with the City of Hamilton handled", "Waterproofing and underpinning coordinated"],
        "hero": ("1513694203232-719a280e022f", "Finished basement living space in an older Hamilton home",
                 "a finished TrustBuildGTA basement or kitchen in Hamilton, landscape"),
        "intro_h2": "Old houses below the escarpment, newer ones above it",
        "intro": [
            "Hamilton has the oldest housing we work in. Below the escarpment, in Westdale, Dundas and the older streets downtown, there are century homes on stone or block foundations. Up on the Mountain and in Ancaster and Stoney Creek, it's mostly postwar and newer homes.",
            "That split shapes the work. Older homes usually need basement waterproofing, underpinning or updated wiring before the finishing starts. Newer ones are more about kitchens, bathrooms and backyards.",
        ],
        "hoods": [
            ("Westdale", "Century homes near McMaster. Basement waterproofing, bathrooms and careful kitchen work around plaster and trim."),
            ("Dundas", "Older homes in the valley with stone foundations and wet basements. Waterproofing and underpinning come first."),
            ("Ancaster", "Larger homes and lots. Kitchens, ensuites, and backyards with retaining walls."),
            ("Stoney Creek", "Family homes from the seventies onward. Basements, flooring and patios."),
            ("The Mountain", "Postwar bungalows and split-levels. Basement suites and main-floor kitchens."),
            ("Kirkendall and Locke Street", "Older semis and detached homes. Kitchens, bathrooms and basements that need waterproofing."),
        ],
        "faq": [
            ("Can you waterproof an old stone foundation?", "Yes, but the method depends on the wall. Most older Hamilton basements need exterior excavation and a membrane, or interior drainage to a sump, before finishing. We tell you which one your house needs at the site visit, and why."),
            ("What is underpinning and do I need it?", "Underpinning lowers a basement floor by digging below the existing footings in sections and pouring new ones deeper. It is how you get usable ceiling height in an old basement. It needs an engineer and a permit, and we coordinate both."),
            ("Do you handle building permits with the City of Hamilton?", "Yes. Where the Ontario Building Code calls for a permit, we prepare the drawings, apply to the City of Hamilton and book the inspections. The permit fee is shown on your quote."),
        ],
    },
]

# Same four steps as the homepage process section, reused on city pages
PROCESS = [
    ("Site visit and measure", "We measure every room we're touching and check the things that change a price: panel capacity, drain locations, moisture on the foundation, what's under the old floor.", "a visit from the person who would actually run your job, not a salesperson."),
    ("Written quote and design", "A line-item quote with a fixed price and HST on its own line. Layout drawings and finish selections get settled here, before a single trade is booked.", "the fixed-price quote, drawings, a materials list and a start date."),
    ("Build with a dedicated lead", "One project lead runs the job from demolition to final paint. They book trades, meet the inspector and send you a short update at the end of each day.", "one phone number for the whole job and a swept, cleared site every evening."),
    ("Walkthrough and warranty", "We walk every room with you and write down anything that isn't right. It gets fixed before the final payment is due.", "a closed permit, product warranties and a written workmanship warranty."),
]
